### ISSUE TITLE
Use cmis:contentStreamFileName instead of cmis:Name as a local filename

### ISSUE THREAD

**Issue by turchinc** [aegif/CmisSync#395]
Other clients seem to have standardized on "cmis:Name" as the display name - our server implementation (based on Chemistry) uses an internal identifier for  "cmis:contentStreamFileName" that a user cannot influence.

**Comment by nicolas-raoul** [comment]
It seems that Documentum also does this, with for instance cmis:name=MyDoc and cmis:contentStreamFileName=MyDoc.zip

**Comment by nicolas-raoul** [comment]
Hi Chris,
I created an experimental CmisSync version that uses cmis:contentStreamFileName instead of cmis:Name as a local filename
Could you please try it and report any bug you find?
Download: https://bitbucket.org/aegif/cmissync/downloads/CmisSync.2.7.0.0.exe
Thanks!

**Comment by turchinc** [comment]
Hi Nicolas,

Will have a look tomorrow!

Best
-c

**Comment by nicolas-raoul** [comment]
Sorry hold your breath, I have found another bug... the next version at https://bitbucket.org/aegif/cmissync/downloads will be better.

**Comment by nicolas-raoul** [comment]
Fixed, please let me know about 2.7.1 :-)

**Comment by nicolas-raoul** [comment]
@turchinc: I just released 2.7.3 could you please try it? Be sure to make backups before, there might be other bugs.
Waiting for your feedback :-)
Nicolas

**Comment by turchinc** [comment]
Bonjour Nicolas

I tried out the new version and mostly it seems to work, I noticed it does
not want to sync a particular file, and gives a very strange error, see
further below.

Also I noticed the version number ist wrong:
[image: pasted1]
Also, have you seen this?
http://www.graudata.com/english/synchronization
I stumbled onto them in github over the weekend because I was looking at
mobile cmis clients and their android app is pretty slick (but somehow
doesn't work with larger files, at least in my tests).

Cheers
-chris


2016-04-04 18:17:26,432 [3] DEBUG CmisSync.Lib.SyncItem [(null)] -
File.Exists(C:?Users?chris.turchin.BIG?CmisSync?CLOUD?DAMDOCS\Adobe Drive
Connector\mc.cmisclient_1.0.52.jar) = False
2016-04-04 18:17:26,433 [3] INFO
 CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - New remote file:
/DAM Group documents/Adobe Drive Connector/mc.cmisclient_1.0.52.jar
2016-04-04 18:17:26,433 [3] DEBUG CmisSync.StatusIconController [(null)] -
StatusIconController OnSyncing
2016-04-04 18:17:26,436 [3] INFO
 CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Downloading:
mc.cmisclient_1.0.52.jar
2016-04-04 18:17:26,496 [3] ERROR
CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not download
file: C:?Users?chris.turchin.BIG?CmisSync?CLOUD?DAMDOCS\Adobe Drive
Connector\mc.cmisclient_1.0.52.jar
System.IO.DirectoryNotFoundException: Could not find a part of the path
'C:\Users\chris.turchin.BIG\Downloads\?Users?chris.turchin.BIG?CmisSync?CLOUD?DAMDOCS\Adobe
Drive Connector\mc.cmisclient_1.0.52.jar.sync'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess
access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize,
FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean
bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess
access, FileShare share)
   at System.IO.File.OpenWrite(String path)
   at
CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.DownloadStream(IContentStream
contentStream, String filePath)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.DownloadFile(IDocument
remoteDocument, String remotePath, String localFolder)
2016-04-04 18:17:26,565 [3] INFO
 CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Removing remotely
deleted file: C:\Users\chris.turchin.BIG\CmisSync\CLOUD\DAMDOCS\Adobe Drive
Connector\mc.cmisclient_1.0.50.jar
2016-04-04 18:17:26,565 [3] DEBUG CmisSync.StatusIconController [(null)] -
StatusIconController OnSyncing
2016-04-04 18:17:27,387 [3] INFO  CmisSync.Lib.Database.Database [(null)] -
Database ChangeLog token set to:

**Comment by nicolas-raoul** [comment]
Thanks for reporting this bug!

Yes, they are one of the CmisSync forks we are the proudest of :-) We actually collaborate actively, for instance they brought many improvements to the underlying CMIS library.
But their Android app does not do synchronization, if I remember correctly? I would be happy to be proved wrong.

**Comment by turchinc** [comment]
small world. many years ago (must have been around 2003?) i had our product
(the predecssor to mediacockpit) certified on their grau hardware /
software storage system :-)
