### ISSUE TITLE
WebException: The request was aborted: The request was canceled

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#418]
When uploading CmisSync_1.0.13.msi (2,799,616 bytes).

It does not happen for a smaller file (1,348,608 bytes).

```
CmisSync.Lib.Cmis.BaseException: Cannot access https://myserver:11222/alfresco/service/cmis/s/workspace:SpacesStore/i/29ba0eab-a803-409e-8778-9c4e92bf6e07/children: The request was aborted: The request was canceled. ---> DotCMIS.Exceptions.CmisConnectionException: Cannot access https://myserver:11222/alfresco/service/cmis/s/workspace:SpacesStore/i/29ba0eab-a803-409e-8778-9c4e92bf6e07/children: The request was aborted: The request was canceled. ---> System.Net.WebException: The request was aborted: The request was canceled.
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
   at System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharChecking(Char* pSrcBegin, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteRaw(Char[] buffer, Int32 index, Int32 count)
   at System.Xml.XmlRawWriterBase64Encoder.WriteChars(Char[] chars, Int32 index, Int32 count)
   at System.Xml.Base64Encoder.Encode(Byte[] buffer, Int32 index, Int32 count)
   at System.Xml.XmlRawWriter.WriteBase64(Byte[] buffer, Int32 index, Int32 count)
   at System.Xml.XmlWellFormedWriter.WriteBase64(Byte[] buffer, Int32 index, Int32 count)
   at DotCMIS.Binding.AtomPub.AtomEntryWriter.WriteContent(XmlWriter writer) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\binding\atompub\atompub-writer.cs:line 194
   at DotCMIS.Binding.AtomPub.AtomEntryWriter.Write(Stream outStream) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\binding\atompub\atompub-writer.cs:line 137
   at DotCMIS.Binding.Impl.HttpUtils.Invoke(UrlBuilder url, String method, String contentType, Output writer, BindingSession session, Nullable`1 offset, Nullable`1 length, IDictionary`2 headers) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\binding\http.cs:line 181
   --- End of inner exception stack trace ---
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.ProcessRecoverableException(String logMessage, Exception exception) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\SynchronizedFolder.cs:line 693
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlLocalFile(String filePath, IFolder remoteFolder, IList`1 remoteFiles) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\CrawlStrategy.cs:line 554
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlLocalFiles(String localFolder, IFolder remoteFolder, IList`1 remoteFiles) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\CrawlStrategy.cs:line 445
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlDescendants(IFolder remoteFolder, IList`1 children, String localFolder) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\CrawlStrategy.cs:line 165
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlSync(IFolder remoteFolder, String localFolder) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\CrawlStrategy.cs:line 82
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.Sync(Boolean syncFull) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\SynchronizedFolder.cs:line 508
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.<.ctor>b__4(Object o, DoWorkEventArgs args) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\SynchronizedFolder.cs:line 222
   --- End of inner exception stack trace ---
```

**Comment by stuartbuckell** [comment]
We are now getting the same problem with Alfresco 5 over HTTP and HTTPS for larger files which take a while to upload.  If uploaded via AWS Windows machine, no problems - over ASDL upload at 50kb/sec even a 6MB file won't upload.   Uploads fine via Alfresco web interface.

**Comment by rosenkra** [comment]
Hi, I had to downgrade to version 1.1.1.0 in order to get it to work again. That was the last version I know it's working okay for me. Maybe higher versions than 1.1.1.0 are okay as well. I didn't try.

I'm waiting desparately for the fix. Your tool is great and I cannot work without it any longer. :)
Thank you so much for your effort!

**Comment by stuartbuckell** [comment]
Nicolas, do you have an update for us?

**Comment by nicolas-raoul** [comment]
Everyone:

1) Are you getting the exact same stacktrace, including `SynchronizedFolder.CrawlLocalFile`?

2) Does CmisSync.1.1.2.0.exe work or not? If yes, what is the last version that works? All past versions can be found at https://bitbucket.org/aegif/cmissync/downloads

If we find what exact commit broke CmisSync, it will be easier to fix. All commits can be found here, including version bumps: https://github.com/aegif/CmisSync/commits/master

Thanks a lot for your feedback!

**Comment by rosenkra** [comment]
Hi,

version 1.2.4 is working
version 1.2.13 is not.

I will now check the versions in between.

**Comment by rosenkra** [comment]
Okay, it looks like 1.2.7 is the last version that's okay.
A quick retest with version 1.2.8 showed the same error popping up (sorry for posting the whole stuff in this discussion):
BTW: "Die Anfrage wurde abgebrochen" means "The request has been cancelled"

`2015-04-22 08:14:06,541 [4] INFO  CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Uploading: D:\<some path here>\10 In-Progress\Atomium_R51_BD_Tactical_Campaigns_v1-01 - Del.docx
2015-04-22 08:15:06,585 [4] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not upload file: D:\<some path here>\10 In-Progress\Atomium_R51_BD_Tactical_Campaigns_v1-01 - Del.docx
DotCMIS.Exceptions.CmisConnectionException: Cannot access <some URL here>: Die Anfrage wurde abgebrochen: Die Anfrage wurde abgebrochen.. ---> System.Net.WebException: Die Anfrage wurde abgebrochen: Die Anfrage wurde abgebrochen..
   bei System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   bei System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   bei System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
   bei System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharChecking(Char* pSrcBegin, Char* pSrcEnd)
   bei System.Xml.XmlUtf8RawTextWriter.WriteRaw(Char[] buffer, Int32 index, Int32 count)
   bei System.Xml.XmlRawWriterBase64Encoder.WriteChars(Char[] chars, Int32 index, Int32 count)
   bei System.Xml.Base64Encoder.Encode(Byte[] buffer, Int32 index, Int32 count)
   bei System.Xml.XmlRawWriter.WriteBase64(Byte[] buffer, Int32 index, Int32 count)
   bei System.Xml.XmlWellFormedWriter.WriteBase64(Byte[] buffer, Int32 index, Int32 count)
   bei DotCMIS.Binding.AtomPub.AtomEntryWriter.WriteContent(XmlWriter writer)
   bei DotCMIS.Binding.AtomPub.AtomEntryWriter.Write(Stream outStream)
   bei DotCMIS.Binding.Impl.HttpUtils.Invoke(UrlBuilder url, String method, String contentType, Output writer, BindingSession session, Nullable`1 offset, Nullable`1 length, IDictionary`2 headers)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei DotCMIS.Binding.Impl.HttpUtils.Invoke(UrlBuilder url, String method, String contentType, Output writer, BindingSession session, Nullable`1 offset, Nullable`1 length, IDictionary`2 headers)
   bei DotCMIS.Binding.Impl.HttpUtils.InvokePOST(UrlBuilder url, String contentType, Output writer, BindingSession session)
   bei DotCMIS.Binding.AtomPub.AbstractAtomPubService.Post(UrlBuilder url, String contentType, Output writer)
   bei DotCMIS.Binding.AtomPub.ObjectService.CreateDocument(String repositoryId, IProperties properties, String folderId, IContentStream contentStream, Nullable`1 versioningState, IList`1 policies, IAcl addAces, IAcl removeAces, IExtensionsData extension)
   bei DotCMIS.Client.Impl.Session.CreateDocument(IDictionary`2 properties, IObjectId folderId, IContentStream contentStream, Nullable`1 versioningState, IList`1 policies, IList`1 addAces, IList`1 removeAces)
   bei DotCMIS.Client.Impl.Folder.CreateDocument(IDictionary`2 properties, IContentStream contentStream, Nullable`1 versioningState, IList`1 policies, IList`1 addAces, IList`1 removeAces, IOperationContext context)
   bei DotCMIS.Client.Impl.Folder.CreateDocument(IDictionary`2 properties, IContentStream contentStream, Nullable`1 versioningState)
   bei CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.UploadFile(String filePath, IFolder remoteFolder)
2015-04-22 08:15:06,589 [4] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not crawl sync local file: D:\<some path here>\10 In-Progress\Atomium_R51_BD_Tactical_Campaigns_v1-01 - Del.docx
DotCMIS.Exceptions.CmisConnectionException: Cannot access <some URL here>: Die Anfrage wurde abgebrochen: Die Anfrage wurde abgebrochen.. ---> System.Net.WebException: Die Anfrage wurde abgebrochen: Die Anfrage wurde abgebrochen..
   bei System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   bei System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   bei System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
   bei System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharChecking(Char* pSrcBegin, Char* pSrcEnd)
   bei System.Xml.XmlUtf8RawTextWriter.WriteRaw(Char[] buffer, Int32 index, Int32 count)
   bei System.Xml.XmlRawWriterBase64Encoder.WriteChars(Char[] chars, Int32 index, Int32 count)
   bei System.Xml.Base64Encoder.Encode(Byte[] buffer, Int32 index, Int32 count)
   bei System.Xml.XmlRawWriter.WriteBase64(Byte[] buffer, Int32 index, Int32 count)
   bei System.Xml.XmlWellFormedWriter.WriteBase64(Byte[] buffer, Int32 index, Int32 count)
   bei DotCMIS.Binding.AtomPub.AtomEntryWriter.WriteContent(XmlWriter writer)
   bei DotCMIS.Binding.AtomPub.AtomEntryWriter.Write(Stream outStream)
   bei DotCMIS.Binding.Impl.HttpUtils.Invoke(UrlBuilder url, String method, String contentType, Output writer, BindingSession session, Nullable`1 offset, Nullable`1 length, IDictionary`2 headers)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.ProcessRecoverableException(String logMessage, Exception exception)
   bei CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.UploadFile(String filePath, IFolder remoteFolder)
   bei CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlLocalFile(String filePath, IFolder remoteFolder, IList`1 remoteFiles)
2015-04-22 08:15:06,589 [4] INFO  CmisSync.Lib.RepoBase [(null)] - Sync Error: Cannot access <some URL here>: Die Anfrage wurde abgebrochen: Die Anfrage wurde abgebrochen..
2015-04-22 08:15:06,590 [4] ERROR CmisSync.StatusIconController [(null)] - Error syncing '320 Release 5.1': Cannot access <some URL here>: Die Anfrage wurde abgebrochen: Die Anfrage wurde abgebrochen..
CmisSync.Lib.Cmis.BaseException: Cannot access <some URL here>: Die Anfrage wurde abgebrochen: Die Anfrage wurde abgebrochen.. ---> DotCMIS.Exceptions.CmisConnectionException: Cannot access <some URL here>: Die Anfrage wurde abgebrochen: Die Anfrage wurde abgebrochen.. ---> System.Net.WebException: Die Anfrage wurde abgebrochen: Die Anfrage wurde abgebrochen..
   bei System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   bei System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   bei System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
   bei System.Xml.XmlUtf8RawTextWriter.WriteRawWithCharChecking(Char* pSrcBegin, Char* pSrcEnd)
   bei System.Xml.XmlUtf8RawTextWriter.WriteRaw(Char[] buffer, Int32 index, Int32 count)
   bei System.Xml.XmlRawWriterBase64Encoder.WriteChars(Char[] chars, Int32 index, Int32 count)
   bei System.Xml.Base64Encoder.Encode(Byte[] buffer, Int32 index, Int32 count)
   bei System.Xml.XmlRawWriter.WriteBase64(Byte[] buffer, Int32 index, Int32 count)
   bei System.Xml.XmlWellFormedWriter.WriteBase64(Byte[] buffer, Int32 index, Int32 count)
   bei DotCMIS.Binding.AtomPub.AtomEntryWriter.WriteContent(XmlWriter writer)
   bei DotCMIS.Binding.AtomPub.AtomEntryWriter.Write(Stream outStream)
   bei DotCMIS.Binding.Impl.HttpUtils.Invoke(UrlBuilder url, String method, String contentType, Output writer, BindingSession session, Nullable`1 offset, Nullable`1 length, IDictionary`2 headers)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.ProcessRecoverableException(String logMessage, Exception exception)
   bei CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlLocalFile(String filePath, IFolder remoteFolder, IList`1 remoteFiles)
   bei CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlLocalFiles(String localFolder, IFolder remoteFolder, IList`1 remoteFiles)
   bei CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlDescendants(IFolder remoteFolder, IList`1 children, String localFolder)
   bei CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlDescendants(IFolder remoteFolder, IList`1 children, String localFolder)
   bei CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlSync(IFolder remoteFolder, String localFolder)
   bei CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.Sync(Boolean syncFull)
   bei CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.<.ctor>b__4(Object o, DoWorkEventArgs args)
   --- Ende der internen Ausnahmestapelüberwachung ---`

**Comment by nicolas-raoul** [comment]
Here are all the changes between 1.2.7 and 1.2.8:
https://github.com/aegif/CmisSync/compare/de967a4807cf37fd83404c7922e08b543df94b2e...f9dfd0d70b036a7f63d65301d1599105a329f2b7

In particular, SessionParameter.ConnectTimeout has been reduced from -1 (infinite) to 60000 (one minute).

Everyone, could you tell me whether it happens only on slow servers, or only when the server is waking up from sleep, or starting, or for any reason taking more than a minute to send a reply?

Increasing ConnectTimeout might be a solution... after how much time should we consider that the server is hopelessly unreachable?

**Comment by rosenkra** [comment]
That's a big problem. Because from 1.2.8 the error is depending on the speed of the connection.
This morning I used my ADSL connection from home to do the tests. The file could be synced with version 1.2.7 but not with version 1.2.8.
But now that I'm in the office I synced successfully the same file with version 1.2.8.

So it depends on the bandwidth of the connection? If the file can be transferred to the server within a minute than it's considered okay? That's a pity. Is there no better way to determine if the connection is (still) valid or not?

**Comment by stuartbuckell** [comment]
Yes this is exactly the same issue as us @nicolas-raoul - with ADSL it won't sync.  With our new 20MB upload pipe it's fine.   IT seems this "1 minute timeout" means, you can upload a file for a maximum of 1 minute.  The timeout should not be called if an upload is in progress. Can you change this to check?

**Comment by nicolas-raoul** [comment]
Here is the code: https://github.com/aegif/CmisSync/blob/master/CmisSync.Auth/Auth.cs#L72

There are 2 settings currently defined:

- ConnectTimeout: 1 minute
- ReadTimeout: 20 minutes

ConnectTimeout is when establishing the network connection, so the size of the file should not matter in principle (in practice it might be different, or maybe I misunderstand something). For big files, I believe ReadTimeout is used (I wonder whether there is a "WriteTimeout" as well).

When you try to upload a huge file on a very narrow connection, after exactly how many seconds does the error appear?

**Comment by rosenkra** [comment]
It appears exactly after 60 seconds:

2015-04-22 07:40:56,728 [6] INFO  CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Uploading: D:\XYZ.docx
2015-04-22 07:41:56,788 [6] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not upload file: D:\XYZ.docx

:-(

**Comment by nicolas-raoul** [comment]
I began adding a WriteTimeout to CmisSync, but to my suprise it appears that DotCMIS actually already uses the value of ReadTimeout as a WriteTimeout:

https://github.com/aegif/chemistry-dotcmis/blob/trunk/DotCMIS/binding/http.cs#L155

So the write timeout should be 20 minutes with CmisSync 2.3.3 not 1 minute as it actually is (as Rosenkra points out).
It sounds like a problem in DotCMIS.
Actually we are planning to replace DotCMIS with PortCMIS, which promises to be more modern and performant, so I am not sure it is worth fixing DotCMIS... if anyone finds the root of the problem we would be glad to fix it, though.

**Comment by stuartbuckell** [comment]
Sure, but in the meanwhile we would really appreciate it if you would revert the timeout change so we can use the connector :)  Well spotted finding the issue - looking forward to PortCMIS.

**Comment by nicolas-raoul** [comment]
As a trial I just released CmisSync 2.3.4 with infinite read/write timeout: https://bitbucket.org/aegif/cmissync/downloads
Could you please test it and tell me whether it solves the problem or not?
Thanks for the feedback!

Source code: https://github.com/aegif/CmisSync/blob/master/CmisSync.Auth/Auth.cs#L80

**Comment by nicolas-raoul** [comment]
I also created 2.3.5 with ConnectTimeout 3 minutes, ReadWriteTimeout 20 minutes
Could you please test them both?
Thanks!

**Comment by rosenkra** [comment]
I created a 37MB test file to sync (because I'm in the office with a better bandwidth):
2.3.3 aborts after 60 seconds
2.3.4 aborts after 60 seconds
2.3.5 aborts after 180 seconds

:( Any ideas?

**Comment by stuartbuckell** [comment]
Florian - are you able to upload the same file via Alfresco GUI ? (assuming you're using that)

**Comment by nicolas-raoul** [comment]
I just created CmisSync 2.3.6 with infinite ConnectTimeout and ReadTimeout.
@rosenkra Does 2.3.6 work better?
@stuartbuckell Can you reproduce the results of Florian's last comment?

**Comment by rosenkra** [comment]
2.3.6 file has been synced in 4min 20 secs

Looks good :-)

**Comment by rosenkra** [comment]
What now? I think we can leave it like that, can't we? Looking forward to PortCMIS.

Thanks to everybody involved and pls keep up the good work.

Cheers,
Florian
![blood-sport-okay-usa](https://cloud.githubusercontent.com/assets/5550914/7295773/b6d37bc0-e9b9-11e4-9715-5c1c432dcfbf.gif)

**Comment by stuartbuckell** [comment]
Great - good job everyone

**Comment by nicolas-raoul** [comment]
A customer is having a case where CmisSync just waits forever on a web request. Rare but it happens about once per day maybe because of their network environment.
So, I changed the timeout to one hour and six hours. That fixes the problem. Please let me know if there is any negative consequence. Thanks!
