### ISSUE TITLE
Parse error - sync causes various errors

### ISSUE THREAD

**Issue by stuartbuckell** [aegif/CmisSync#514]
Hi,

I've installed the latest release.  No files changed on the remote repo, but these errors occured.  As you can see it sync'd afterwards, but I am not sure why the initial errors?  Do you need more info from me?

Windows 8
CMISSync 2.1.3.0
Alfresco 5

2015-01-15 09:51:15,950 [8] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not crawl folder: /Sites/cpw/documentLibrary
DotCMIS.Exceptions.CmisConnectionException: Parsing exception! ---> System.InvalidOperationException: There is an error in XML document (1, 257650). ---> System.Net.WebException: The operation has timed out.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.Xml.XmlTextReaderImpl.ReadData()
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.ReadEndElement()
   at System.Xml.Serialization.XmlSerializationReader.ReadEndElement()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read7_cmisPropertyId(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read11_cmisPropertiesType(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read20_cmisObjectType(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read21_object()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.DeserializeObject(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.ParseElement(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.ParseEntry(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.ParseFeed(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.Parse()
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Parse[T](Stream stream)
   --- End of inner exception stack trace ---
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Parse[T](Stream stream)
   at DotCMIS.Binding.AtomPub.NavigationService.GetChildren(String repositoryId, String folderId, String filter, String orderBy, Nullable`1 includeAllowableActions, Nullable`1 includeRelationships, String renditionFilter, Nullable`1 includePathSegment, Nullable`1 maxItems, Nullable`1 skipCount, IExtensionsData extension)
   at DotCMIS.Client.Impl.Folder.<>c__DisplayClass5.<GetChildren>b__4(Int64 maxNumItems, Int64 skipCount)
   at DotCMIS.Client.Impl.PageFetcher`1.FetchNextPage(Int64 skipCount)
   at DotCMIS.Client.Impl.AbstractEnumerator`1.GetCurrentPage()
   at DotCMIS.Client.Impl.CollectionEnumerator`1.MoveNext()
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlRemote(IFolder remoteFolder, String localFolder, IList`1 remoteFiles, IList`1 remoteFolders)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlSync(IFolder remoteFolder, String localFolder)
2015-01-15 09:51:15,962 [8] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not crawl sync remote folder: /Sites/cpw/documentLibrary
DotCMIS.Exceptions.CmisConnectionException: Parsing exception! ---> System.InvalidOperationException: There is an error in XML document (1, 257650). ---> System.Net.WebException: The operation has timed out.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.Xml.XmlTextReaderImpl.ReadData()
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.ReadEndElement()
   at System.Xml.Serialization.XmlSerializationReader.ReadEndElement()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read7_cmisPropertyId(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read11_cmisPropertiesType(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read20_cmisObjectType(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read21_object()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.DeserializeObject(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.ParseElement(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.ParseEntry(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.ParseFeed(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.Parse()
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Parse[T](Stream stream)
   --- End of inner exception stack trace ---
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.ProcessRecoverableException(String logMessage, Exception exception)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlSync(IFolder remoteFolder, String localFolder)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlRemoteFolder(IFolder remoteSubFolder, String localFolder, IList`1 remoteFolders)
2015-01-15 09:51:15,963 [8] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not crawl folder: /Sites/cpw
DotCMIS.Exceptions.CmisConnectionException: Parsing exception! ---> System.InvalidOperationException: There is an error in XML document (1, 257650). ---> System.Net.WebException: The operation has timed out.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.Xml.XmlTextReaderImpl.ReadData()
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.ReadEndElement()
   at System.Xml.Serialization.XmlSerializationReader.ReadEndElement()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read7_cmisPropertyId(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read11_cmisPropertiesType(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read20_cmisObjectType(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read21_object()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.DeserializeObject(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.ParseElement(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.ParseEntry(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.ParseFeed(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.Parse()
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Parse[T](Stream stream)
   --- End of inner exception stack trace ---
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.ProcessRecoverableException(String logMessage, Exception exception)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlRemoteFolder(IFolder remoteSubFolder, String localFolder, IList`1 remoteFolders)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlRemote(IFolder remoteFolder, String localFolder, IList`1 remoteFiles, IList`1 remoteFolders)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlSync(IFolder remoteFolder, String localFolder)
2015-01-15 09:51:15,963 [8] INFO  CmisSync.Lib.RepoBase [(null)] - Sync Error: CmisSync.Lib.Cmis.BaseException, Parsing exception!
2015-01-15 09:51:15,964 [8] ERROR CmisSync.StatusIconController [(null)] - Error syncing 'cpw': Parsing exception!
CmisSync.Lib.Cmis.BaseException: Parsing exception! ---> DotCMIS.Exceptions.CmisConnectionException: Parsing exception! ---> System.InvalidOperationException: There is an error in XML document (1, 257650). ---> System.Net.WebException: The operation has timed out.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.Xml.XmlTextReaderImpl.ReadData()
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.ReadEndElement()
   at System.Xml.Serialization.XmlSerializationReader.ReadEndElement()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read7_cmisPropertyId(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read11_cmisPropertiesType(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read20_cmisObjectType(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read21_object()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.DeserializeObject(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.ParseElement(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.ParseEntry(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.ParseFeed(XmlReader reader)
   at DotCMIS.Binding.AtomPub.AtomPubParser.Parse()
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Parse[T](Stream stream)
   --- End of inner exception stack trace ---
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.ProcessRecoverableException(String logMessage, Exception exception)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlSync(IFolder remoteFolder, String localFolder)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.Sync(Boolean syncFull)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.<.ctor>b__4(Object o, DoWorkEventArgs args)
   --- End of inner exception stack trace ---
2015-01-15 09:51:15,976 [8] INFO  CmisSync.Lib.RepoBase [(null)] - Full Sync Complete: C:\Users\stuart\CmisSync\cpw

**Comment by nicolas-raoul** [comment]
Have all files been correctly synchronized?
The message "Full Sync Complete" is displayed at the end of every sync cycle, even if some of the operations have failed.

Would you be able to observe network traffic using a tool like Wireshark, to see what request/response matches the error stack?

Also, does any error appear in alfresco.log?

**Comment by stuartbuckell** [comment]
I get sync errors now with every file, using the latest version.  I will attempt a re-install.   The file gets uploaded however.  I will dig out the logs for you later.

**Comment by stuartbuckell** [comment]
Scratch that, one file uploaded, the other didn't (larger, 6.2mb), it shows as 0 bytes in Alfresco, although the file itself was created.

Is there some file upload limit in force do you think ?

**Comment by stuartbuckell** [comment]
at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.ProcessRecoverableException(String logMessage, Exception exception)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlLocalFile(String filePath, IFolder remoteFolder, IList`1 remoteFiles)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlLocalFiles(String localFolder, IFolder remoteFolder, IList`1 remoteFiles)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlSync(IFolder remoteFolder, String localFolder)
2015-01-17 15:03:27,703 [6] INFO  CmisSync.Lib.RepoBase [(null)] - Sync Error: CmisSync.Lib.Cmis.BaseException, Cannot access https://__removed___/alfresco/cmisatom/185f89007-a43a-426a-9248-fe857c0722ae/content?id=workspace://SpacesStore/a4c05129-853c-4ad0-b289-1974f6f01bb1;1.0&overwriteFlag=true: The request was aborted: The request was canceled.
2015-01-17 15:03:27,703 [6] ERROR CmisSync.StatusIconController [(null)] - Error syncing 'Marketing': Cannot access https://__removed___/alfresco/cmisatom/185f89007-a43a-426a-9248-fe857c0722ae/content?id=workspace://SpacesStore/a4c05129-853c-4ad0-b289-1974f6f01bb1;1.0&overwriteFlag=true: The request was aborted: The request was canceled.
CmisSync.Lib.Cmis.BaseException: Cannot access https://__removed___/alfresco/cmisatom/185f89007-a43a-426a-9248-fe857c0722ae/content?id=workspace://SpacesStore/a4c05129-853c-4ad0-b289-1974f6f01bb1;1.0&overwriteFlag=true: The request was aborted: The request was canceled. ---> DotCMIS.Exceptions.CmisConnectionException: Cannot access https://__removed___/alfresco/cmisatom/185f89007-a43a-426a-9248-fe857c0722ae/content?id=workspace://SpacesStore/a4c05129-853c-4ad0-b289-1974f6f01bb1;1.0&overwriteFlag=true: The request was aborted: The request was canceled. ---> System.Net.WebException: The request was aborted: The request was canceled.
   at System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at DotCMIS.Binding.AtomPub.ObjectService.<>c__DisplayClass2.<SetContentStream>b__1(Stream stream)
   at DotCMIS.Binding.Impl.HttpUtils.Invoke(UrlBuilder url, String method, String contentType, Output writer, BindingSession session, Nullable`1 offset, Nullable`1 length, IDictionary`2 headers)
   --- End of inner exception stack trace ---
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.ProcessRecoverableException(String logMessage, Exception exception)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlSync(IFolder remoteFolder, String localFolder)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.Sync(Boolean syncFull)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.<.ctor>b__4(Object o, DoWorkEventArgs args)
   --- End of inner exception stack trace ---

**Comment by stuartbuckell** [comment]
Seems filesize isn't an issue - https://forums.alfresco.com/forum/developer-discussions/alfresco-api/what-max-file-size-allowed-cmis-api-uploading-file

However, we are running Alfresco SSL over NGINX rather than directly to Tomcat - perhaps this is a problem.  I will check with our sys-admin on Monday

**Comment by stuartbuckell** [comment]
One final bit of info; the file uploaded fine via the HTTPS web interface

**Comment by slibert** [comment]
For those (like me) gettings this kind of errors, and having some tags or categories applied to document, could be related to : https://issues.alfresco.com/jira/browse/MNT-10548

**Comment by nicolas-raoul** [comment]
@slibert : Thanks for the tip!
MNT-10548 is marked as "fixed in 4.2.2", and Stuart is using Alfresco 5... do you think the bug has re-appeared?
