### ISSUE TITLE
Alert user when diskis full

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#532]
Currently this shows in the log:

```
2015-03-06 10:41:58,568 [13] INFO  CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Downloading: VideoPhoto.zip
2015-03-06 11:02:17,967 [13] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not download file: C:\Users\win7pro32bit\CmisSync\aegifportal\????\AlfrescoSeminar20090514\VideoPhoto.zip
System.IO.IOException: There is not enough space on the disk.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.FlushWrite(Boolean calledFromFinalizer)
   at System.IO.FileStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.DownloadStream(IContentStream contentStream, String filePath) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\SynchronizedFolder.cs:line 1211
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.DownloadFile(IDocument remoteDocument, String localFolder) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\SynchronizedFolder.cs:line 1077
2015-03-06 11:02:18,967 [13] ERROR CmisSync.Lib.Database.Database [(null)] - Could not execute SQL: INSERT OR REPLACE INTO folders (path, localPath, id, serverSideModificationDate)
                    VALUES (@path, @localPath, @id, @serverSideModificationDate); {"path":"????/ITMedia???????????","localPath":"????\\ITMedia???????????","id":"a550cf64-7e2e-4f25-a1f2-5e88ffa6acda","serverSideModificationDate":"2012-07-11T07:03:04.23Z"}
System.Data.SQLite.SQLiteException (0x80004005): database or disk is full
database or disk is full
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLite3.cs:line 484
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLite3.cs:line 426
   at System.Data.SQLite.SQLiteDataReader.NextResult() in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteDataReader.cs:line 1280
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteDataReader.cs:line 108
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteCommand.cs:line 610
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery() in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteCommand.cs:line 644
   at CmisSync.Lib.Database.Database.ExecuteSQLAction(String text, Dictionary`2 parameters) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Database\Database.cs:line 1137
2015-03-06 11:02:19,019 [13] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not crawl sync remote folder: /Sites/aegifportal/documentLibrary/????
System.Data.SQLite.SQLiteException (0x80004005): database or disk is full
database or disk is full
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLite3.cs:line 484
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLite3.cs:line 426
   at System.Data.SQLite.SQLiteDataReader.NextResult() in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteDataReader.cs:line 1280
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteDataReader.cs:line 108
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior) in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteCommand.cs:line 610
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery() in c:\dev\sqlite\dotnet\System.Data.SQLite\SQLiteCommand.cs:line 644
   at CmisSync.Lib.Database.Database.ExecuteSQLAction(String text, Dictionary`2 parameters) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Database\Database.cs:line 1142
   at CmisSync.Lib.Database.Database.AddFolder(SyncItem item, String objectId, Nullable`1 serverSideModificationDate) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Database\Database.cs:line 441
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.DownloadDirectory(IFolder remoteFolder, String localFolder) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\SynchronizedFolder.cs:line 709
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.RecursiveFolderCopy(IFolder remoteFolder, String localFolder) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\SynchronizedFolder.cs:line 657
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlRemoteFolder(IFolder remoteSubFolder, String localFolder, IList`1 remoteFolders) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\CrawlStrategy.cs:line 303
```

**Comment by nicolas-raoul** [comment]
Sometimes a full disk can corrupt the .cmissync files, and prevent CmisSync from starting.

In such cases, a workaround is to delete all .cmissync files in `C:\Users\<your_user>\AppData\Roaming\cmissync\`.
