### ISSUE TITLE
Test CmisSync in multi-parents repository

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#533]
From the forum:

> Alfresco is able to handle multiple
parents:
<http://blogs.alfresco.com/wp/rfernandes/2013/09/25/alfresco-parents-and-children/>
section "Multiple Parents".
It is currently not available to end users on the web frontend by
default. But this feature is used by Alfresco's Add-on Records
Management. And IIRC there is also an extension that offers that feature
on the web frontend even without Records Management.

**Comment by bpeters09** [comment]
This is currently listed as an enhancement, but it might also be a bug. 

When I browse a folder in CMIS Workbench with documents including some that have the folder as a seconday parent, I can see all files including the once that have a seconday parent. 
![screen shot 2015-04-22 at 06 44 30](https://cloud.githubusercontent.com/assets/1982588/7275934/86cc7052-e8bb-11e4-9fd1-7b510009bb1b.png)

When I sync a folder using CmisSync the documents that have the folder as a secondary parent are not synced.
![screen shot 2015-04-22 at 06 44 12](https://cloud.githubusercontent.com/assets/1982588/7275941/90996f2c-e8bb-11e4-97f7-20dad56a3e21.png)

To reproduce you can either use the Link to action in Alfresco RM or execute a document.addNode(childNode);

Is this related to CmisSync or the DotCMIS library?

**Comment by nicolas-raoul** [comment]
Thanks a lot for the investigation!

Here are the commands that CmisSync uses:

- https://github.com/aegif/CmisSync/blob/master/CmisSync.Lib/Sync/SynchronizedFolder.cs#L631
- https://github.com/aegif/CmisSync/blob/master/CmisSync.Lib/Sync/CrawlStrategy.cs#L207

It looks exactly like your code, right?
So I wonder what is the difference...
Actually CmisSync uses this slightly modified version of DotCMIS: https://github.com/aegif/chemistry-dotcmis Might it be the reason? Sorry for the trouble but would you mind replacing the DotCMIS with this one and let us know whether it is different? Thank you very much!

**Comment by nicolas-raoul** [comment]
Sorry for the newbie question, but are there cases where a folder is filed in one of its children? Such a case might cause an infinite loop in CmisSync.

**Comment by bpeters09** [comment]
I tested the same code but now with the DotCMIS.dll used by CmisSync and it also lists the documents with secondary parents and updates a document properly.

The error in CmisSync cient is recorded in the log as follows:

2015-04-23 00:46:53,049 [8] INFO CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Downloading: InvoiceAdmin.doc
2015-04-23 00:46:53,096 [8] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not download file: \Sites\test\documentLibrary\Documents\InvoiceAdmin.doc
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Sites\test\documentLibrary\Documents\InvoiceAdmin.doc.sync'.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at System.IO.File.OpenWrite(String path)
at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.DownloadStream(IContentStream contentStream, String filePath)
at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.DownloadFile(IDocument remoteDocument, String localFolder)

Looks like it tries to sync using its primary path rather than the secondary path. The primary path is Documents and the secondary path is admin in my test cases. So it might be related to how metadata is stored in the local database?

**Comment by nicolas-raoul** [comment]
@bpeters09 Could you please let me know what Alfresco add-on or setting you use to create secondary paths?
I am beginning to investigate the matter and I trying to figure out what is the easiest way to create such nodes now that Alfresco Explorer is gone :-)
Thanks a lot for your help!

**Comment by cdwi** [comment]
@nicolas-raoul I usually use the JavaScript Console (js-console) to enter the JS code - see code behind the link in the first posting in this thread. But you should also be able to write the JS code, upload it to the data dictionary and execute it there (but not that handy...).

**Comment by bpeters09** [comment]
@nicolas-raoul the JavaScript call 

space.addNode(childNode);

adds the childNode as a secondary parent to space. In the RM module the link to capability using secondary parents is exposed in the Share UI. Most of the time I use a simple rule to automatically add documents as a secondary parent to some other folder to have some sample content.
