### ISSUE TITLE
"CmisRuntimeException: Unauthorized" on SharePoint 2013 with Basic Authentication enabled

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#537]
On SharePoint 2013 with Basic Authentication enabled:

```
2015-03-16 08:51:52,735 [5] DEBUG CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - First sync, invoke a full crawl sync
2015-03-16 08:51:52,925 [5] DEBUG CmisSync.Lib.Cmis.CmisUtils [(null)] - Server token:1;3;f71a6658-3dd6-42ba-a096-a433fe2eca62;635620889797700000;7983;03/16/2015 07:49:40
2015-03-16 08:52:03,886 [5] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not crawl folder: /somefolder
DotCMIS.Exceptions.CmisRuntimeException: Unauthorized
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Read(UrlBuilder url)
   at DotCMIS.Binding.AtomPub.NavigationService.GetChildren(String repositoryId, String folderId, String filter, String orderBy, Nullable`1 includeAllowableActions, Nullable`1 includeRelationships, String renditionFilter, Nullable`1 includePathSegment, Nullable`1 maxItems, Nullable`1 skipCount, IExtensionsData extension)
   at DotCMIS.Client.Impl.Folder.<>c__DisplayClass5.<GetChildren>b__4(Int64 maxNumItems, Int64 skipCount)
   at DotCMIS.Client.Impl.PageFetcher`1.FetchNextPage(Int64 skipCount)
   at DotCMIS.Client.Impl.AbstractEnumerator`1.GetCurrentPage()
   at DotCMIS.Client.Impl.CollectionEnumerator`1.MoveNext()
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlRemote(IFolder remoteFolder, String localFolder, IList`1 remoteFiles, IList`1 remoteFolders)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlSync(IFolder remoteFolder, String localFolder)
```

**Comment by nicolas-raoul** [comment]
Please [contact us](mailto:cmissync@aegif.jp) if you have this problem.
