### ISSUE TITLE
Method not found: Boolean CmisSync.Lib.Config.get_FrozenConfiguration

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#538]
After installing new CmisSync (2.1.3), it refuses to start:

```
2015-03-17 12:01:40,221 [1] INFO  CmisSync.Program [(null)] - Starting. Version: 2.0.6.0
2015-03-17 12:01:40,273 [1] INFO  CmisSync.Lib.FolderLock [(null)] - Creating folder lock file: C:\Users\win7pro32bit\CmisSync
2015-03-17 12:01:40,351 [1] DEBUG CmisSync.SetupController [(null)] - SetupController - Entering constructor.
2015-03-17 12:01:40,352 [1] DEBUG CmisSync.SetupController [(null)] - SetupController - Exiting constructor.
2015-03-17 12:01:40,622 [1] DEBUG CmisSync.Setup [(null)] - Entering constructor.
2015-03-17 12:01:40,624 [1] DEBUG CmisSync.Setup [(null)] - Exiting constructor.
2015-03-17 12:01:40,665 [1] FATAL CmisSync.Program [(null)] - Exception in Program.Main
System.MissingMethodException: Method not found: 'Boolean CmisSync.Lib.Config.get_FrozenConfiguration()'.
   at CmisSync.StatusIcon.CreateMenu()
   at CmisSync.StatusIcon..ctor()
   at CmisSync.GUI.Run()
   at CmisSync.Program.Main(String[] args)
```

**Comment by nicolas-raoul** [comment]
Apparently installing CmisSync over an existing version is sometimes not enough.

The recommended way is:

1. Uninstall the previous CmisSync
2. Install the new CmisSync

Your data and configuration are safe, they will not be removed by uninstalling CmisSync.
