### ISSUE TITLE
Parsing exception!

### ISSUE THREAD

**Issue by lelmarir** [aegif/CmisSync#573]
I get a lot of this, but i can't tell what is the problem.
Would it be possible to store the xml document to a file when this error occurs?

```
2015-06-09 10:28:14,504 [10] INFO  CmisSync.Lib.RepoBase [(null)] - Sync Error: CmisSync.Lib.Cmis.BaseException, Parsing exception!
2015-06-09 10:28:14,504 [10] ERROR CmisSync.StatusIconController [(null)] - Error syncing 'Marchon IT': Parsing exception!
CmisSync.Lib.Cmis.BaseException: Parsing exception! ---> DotCMIS.Exceptions.CmisConnectionException: Parsing exception! ---> System.InvalidOperationException: Errore nel documento XML (1, 16182). ---> System.Xml.XmlException: Fine file imprevista durante l'analisi di Name. Riga 1, posizione 16182.
   in System.Xml.XmlTextReaderImpl.Throw(Exception e)
   in System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   in System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res, String arg)
   in System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   in System.Xml.XmlTextReaderImpl.ParseElement()
   in System.Xml.XmlTextReaderImpl.ParseElementContent()
   in System.Xml.XmlTextReaderImpl.Read()
   in System.Xml.XmlReader.ReadEndElement()
   in System.Xml.Serialization.XmlSerializationReader.ReadEndElement()
   in Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read20_cmisObjectType(Boolean isNullable, Boolean checkType)
   in Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReadercmisObjectType.Read21_object()
   --- Fine della traccia dello stack dell'eccezione interna ---
   in System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   in System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   in DotCMIS.Binding.AtomPub.AtomPubParser.DeserializeObject(XmlReader reader)
   in DotCMIS.Binding.AtomPub.AtomPubParser.ParseElement(XmlReader reader)
   in DotCMIS.Binding.AtomPub.AtomPubParser.ParseEntry(XmlReader reader)
   in DotCMIS.Binding.AtomPub.AtomPubParser.ParseFeed(XmlReader reader)
   in DotCMIS.Binding.AtomPub.AtomPubParser.Parse()
   in DotCMIS.Binding.AtomPub.AbstractAtomPubService.Parse[T](Stream stream)
   --- Fine della traccia dello stack dell'eccezione interna ---
   in CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.ProcessRecoverableException(String logMessage, Exception exception)
   in CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlSync(IFolder remoteFolder, String localFolder)
   in CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlSyncAndUpdateChangeLogToken(IFolder remoteFolder, String localFolder)
   in CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.Sync(Boolean syncFull)
   in CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.<.ctor>b__4(Object o, DoWorkEventArgs args)
   --- Fine della traccia dello stack dell'eccezione interna ---
```

**Comment by nicolas-raoul** [comment]
Could you please run Wireshark to capture the request and response when this happens?
Thanks for the feedback!

**Comment by lelmarir** [comment]
this exception occur sometimes, and till now i was unable to reproduce

using whireshark i can see that cmisync do a lot of requests to the server, is it normal?
Here a packet log: [https://drive.google.com/file/d/0B67mXKBuci7CcHp6U3kzblh1U3c/view?usp=sharing](https://drive.google.com/file/d/0B67mXKBuci7CcHp6U3kzblh1U3c/view?usp=sharing)

**Comment by nicolas-raoul** [comment]
Could you please post the debug_log.txt file too, so that we can match the
error and the request/response? Thanks!

**Comment by lelmarir** [comment]
here the debug_log : https://drive.google.com/open?id=0B67mXKBuci7CdVBPQkVkVlRkTHM&authuser=0

but the packets log I've linked in the previous post is not related to the error (during that period no errors occour)
I can try to start a packets capture and wait until an error occur, but it might be a huge amount of data:
do you need only the data i've sent or the complete packet (headers and data) ?

```
No.     Time           Source                Destination           Protocol Length Request line Info
    128 9.087476000    192.168.1.20          192.168.50.110        HTTP     266    User-Agent: Apache Chemistry DotCMIS\r\n,Authorization: Basic bXByZXRpOkxhY3JvZGltNDd4b2RoOQ==\r\n,Host: 192.168.50.110:8080\r\n GET /alfresco/api/-default-/public/cmis/versions/1.1/atom/type?id=F%3Ast%3Asite HTTP/1.1 
    144 9.097838000    192.168.50.110        192.168.1.20          HTTP/XML 1158                HTTP/1.1 200 OK 
```

**Comment by nicolas-raoul** [comment]
Yes the capture needs to be at the time when the error appears.
You can cut the excess parts before and after to keep only like 3 minutes.
Thanks a lot!

**Comment by digcatmarkp** [comment]
Hi Nicolas

I am using 2.3.3. MacOS client and we are running on Alfresco 5 community edition.

I also get Parsing exception! error showing in the CMIS Sync and thus no syncing occurs after the initial pull down from the repo to the desktop folder (the initial sync seems to work as it should).

Once this first sync is complete any new content or updates to content do not sync in either direction and I see the Parsing exception! warning in the client.

I can provide a debug log and wireshark output. Can you guide me as to what you need from WS, as in what capture filter you need to see?

Thanks

Mark

**Comment by nicolas-raoul** [comment]
Hello @digcatmarkp 
As a capture filter, the important is to see the conversation between your local computer and the Alfresco server.
The easiest might be to first find a packet with the URL of your Alfresco server, and then right-click on it and choose "Follow TCP stream".
Thanks a lot!

**Comment by digcatmarkp** [comment]
Hi Nicholas

Just tested against Mac 2.4.1 version and the Parsing Exception issue 
persists. We will use wireshark to capture the TCP packets to try and 
identify the issue.

The latest version Windows client 2.4.6 seems much more solid thank you. 
We are aware is not working on the versioning of content (even with the 
aspect enabled) as it is a CMIS 1.1 operation and the Sync tool still 
uses CMIS1.0. So this is understandable.

Thanks

Mark

**Comment by sprinz** [comment]
We are getting the same message. Did you solve your problem? We are really desperate to find a solution.

Greets,
Simon

**Comment by nicolas-raoul** [comment]
Anyone getting this problem, please post (or send us to CmisSync@aegif.jp) the Wireshark captures I asked for above.
Without that we can't fix the problem.
Thank you!
Also, what version of Alfresco is everyone using? Or maybe another server?

**Comment by sprinz** [comment]
We have our own backend implementation using OpenCMIS. 

The error occures at some customers and can not be reproduced reliably. Therefore it is very difficult to provide wireshark captures.

**Comment by nicolas-raoul** [comment]
Similar problem reported by another user on 2016/11/23:
```
2016-11-21 20:35:38,695 [3] INFO  CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Added file to database: I:\thefolder\folder2\rather-long-name.pdf
2016-11-21 20:35:38,695 [3] INFO  CmisSync.Lib.Database.Database [(null)] - Database ChangeLog token set to: 
2016-11-21 20:35:38,695 [3] INFO  CmisSync.Lib.RepoBase [(null)] - Full Sync Complete: I:\thefolder
2016-11-21 20:35:43,696 [10] INFO  CmisSync.Lib.RepoBase [(null)] - Full Sync Started: I:\thefolder
2016-11-21 20:35:43,899 [10] DEBUG CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - /Sites/thesite/documentLibrary : I:\thefolder
2016-11-21 20:35:43,899 [10] WARN  CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Invoke a full crawl sync (the remote does not support ChangeLog)
2016-11-21 20:35:44,071 [10] DEBUG CmisSync.Lib.Cmis.CmisUtils [(null)] - Server token:
2016-11-21 20:35:51,845 [10] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not crawl sync remote folder: /Sites/thesite/documentLibrary/folder1
DotCMIS.Exceptions.CmisConnectionException: Parsing exception! ---> System.Xml.XmlException: Élément racine manquant.
   à System.Xml.XmlTextReaderImpl.Throw(Exception e)
   à System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   à System.Xml.XmlTextReaderImpl.Read()
   à System.Xml.XmlReader.MoveToContent()
   à System.Xml.XmlReader.IsStartElement()
   à DotCMIS.Binding.AtomPub.AtomPubParser.Parse()
   à DotCMIS.Binding.AtomPub.AbstractAtomPubService.Parse[T](Stream stream)
   --- Fin de la trace de la pile d'exception interne ---
   à DotCMIS.Binding.AtomPub.AbstractAtomPubService.Parse[T](Stream stream)
   à DotCMIS.Binding.AtomPub.NavigationService.GetChildren(String repositoryId, String folderId, String filter, String orderBy, Nullable`1 includeAllowableActions, Nullable`1 includeRelationships, String renditionFilter, Nullable`1 includePathSegment, Nullable`1 maxItems, Nullable`1 skipCount, IExtensionsData extension)
   à DotCMIS.Client.Impl.Folder.<>c__DisplayClass5.<GetChildren>b__4(Int64 maxNumItems, Int64 skipCount)
   à DotCMIS.Client.Impl.PageFetcher`1.FetchNextPage(Int64 skipCount)
   à DotCMIS.Client.Impl.AbstractEnumerator`1.GetCurrentPage()
   à DotCMIS.Client.Impl.CollectionEnumerator`1.MoveNext()
   à CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlRemote(IFolder remoteFolder, String remotePath, String localFolder, IList`1 remoteFiles, IList`1 remoteFolders)
   à CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlSync(IFolder remoteFolder, String remotePath, String localFolder)
   à CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlRemoteFolder(IFolder remoteSubFolder, String remotePath, String localFolder, IList`1 remoteFolders)
2016-11-21 20:35:51,923 [10] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not access remote object: folder1
```
In that case the folder contains few documents but around 10.000 empty folders. The first synchronization (initial download) works fine, but at the second synchronization fails. Everyone, have you managed to reproduce this error with a folder containing few folders and documents? If always with big numbers of objects, maybe the CMIS XML response is getting too much and DotCMIS fails to parse it?

**Comment by Dnhatsave** [comment]
i got the same error, any workaround for this ??

Im using Alfresco 6.1.

My log file

` ERROR CmisSync.StatusIconController [(null)] - Error syncing 'www.cedsif.gov.mz\cedsif': Parsing exception!
CmisSync.Lib.Cmis.BaseException: Parsing exception! ---> DotCMIS.Exceptions.CmisConnectionException: Parsing exception! ---> System.Xml.XmlException: An error occurred while parsing EntityName. Line 97, position 433.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.SkipPartialTextValue()
   at System.Xml.XmlTextReaderImpl.Read()
   at DotCMIS.Binding.AtomPub.AtomPubParser.Parse()
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Parse[T](Stream stream)
   --- End of inner exception stack trace ---
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Parse[T](Stream stream)
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.GetObjectInternal(String repositoryId, IdentifierType idOrPath, String objectIdOrPath, Nullable`1 returnVersion, String filter, Nullable`1 includeAllowableActions, Nullable`1 includeRelationships, String renditionFilter, Nullable`1 includePolicyIds, Nullable`1 includeAcl, IExtensionsData extension, Boolean outputErrors)
   at DotCMIS.Binding.AtomPub.ObjectService.GetObjectByPath(String repositoryId, String path, String filter, Nullable`1 includeAllowableActions, Nullable`1 includeRelationships, String renditionFilter, Nullable`1 includePolicyIds, Nullable`1 includeAcl, IExtensionsData extension, Boolean outputErrors)
   at DotCMIS.Client.Impl.Session.GetObjectByPath(String path, IOperationContext context, Boolean outputErrors)
   at DotCMIS.Client.Impl.Session.GetObjectByPath(String path, Boolean outputErrors)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.Sync()
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.<>c__DisplayClass35_0.<.ctor>b__0(Object o, DoWorkEventArgs args)
   --- End of inner exception stack trace ---`
