### ISSUE TITLE
Bad Request with Documentum 7.1

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#602]
```
2015-08-19 17:44:20,767 [14] INFO  CmisSync.Lib.RepoBase [(null)] - Sync Error: CmisSync.Lib.Cmis.BaseException, Bad Request
2015-08-19 17:44:20,768 [14] ERROR CmisSync.StatusIconController [(null)] - Error syncing 'documentum71': Bad Request
CmisSync.Lib.Cmis.BaseException: Bad Request ---> DotCMIS.Exceptions.CmisInvalidArgumentException: Bad Request
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Read(UrlBuilder url) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\binding\atompub\atompub.cs:line 439
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.GetObjectInternal(String repositoryId, IdentifierType idOrPath, String objectIdOrPath, Nullable`1 returnVersion, String filter, Nullable`1 includeAllowableActions, Nullable`1 includeRelationships, String renditionFilter, Nullable`1 includePolicyIds, Nullable`1 includeAcl, IExtensionsData extension) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\binding\atompub\atompub.cs:line 799
   at DotCMIS.Binding.AtomPub.ObjectService.GetObjectByPath(String repositoryId, String path, String filter, Nullable`1 includeAllowableActions, Nullable`1 includeRelationships, String renditionFilter, Nullable`1 includePolicyIds, Nullable`1 includeAcl, IExtensionsData extension) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\binding\atompub\atompub.cs:line 1801
   at DotCMIS.Client.Impl.Session.GetObjectByPath(String path, IOperationContext context) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\client\client-impl.cs:line 570
   at DotCMIS.Client.Impl.Session.GetObjectByPath(String path) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\client\client-impl.cs:line 543
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.Sync(Boolean syncFull) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\SynchronizedFolder.cs:line 413
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.<>c__DisplayClass6.<.ctor>b__4(Object o, DoWorkEventArgs args) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\SynchronizedFolder.cs:line 186
   --- End of inner exception stack trace ---
```

**Comment by nicolas-raoul** [comment]
Removing the following lines in `SynchronizedFolder.cs` fixes the problem, not sure about the side effects:

                filters.Add("cmis:contentStreamFileName");
                filters.Add("cmis:contentStreamLength");
