### ISSUE TITLE
Documentum 7.1 Internal Server Error when downloading a document

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#603]
```
2015-08-19 19:01:15,987 [11] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Download failed: feiurhgfoiesgroiehgreoirg
DotCMIS.Exceptions.CmisRuntimeException: Internal Server Error
   at DotCMIS.Binding.AtomPub.ObjectService.GetContentStream(String repositoryId, String objectId, String streamId, Nullable`1 offset, Nullable`1 length, IExtensionsData extension) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\binding\atompub\atompub.cs:line 1835
   at DotCMIS.Client.Impl.Session.GetContentStream(IObjectId docId, String streamId, Nullable`1 offset, Nullable`1 length) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\client\client-impl.cs:line 999
   at DotCMIS.Client.Impl.Document.GetContentStream(String streamId, Nullable`1 offset, Nullable`1 length) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\client\client-objects.cs:line 858
   at DotCMIS.Client.Impl.Document.GetContentStream(String streamId) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\client\client-objects.cs:line 853
   at DotCMIS.Client.Impl.Document.GetContentStream() in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\Extras\OpenDataSpaceDotCMIS\DotCMIS\client\client-objects.cs:line 848
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.DownloadFile(IDocument remoteDocument, String localFolder) in C:\Users\win7pro32bit\Documents\GitHub\CmisSync\CmisSync.Lib\Sync\SynchronizedFolder.cs:line 877
2015-08-19 19:01:16,094 [11] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not download file: \somepath\feiurhgfoiesgroiehgreoirg
```

When trying to download from the Object's `Content URL` within CMIS Workbench:

```
[CMIS AtomPub binding]

STATUS CODE:
500

EXCEPTION:
runtime

ERROR:
Failed to get the content stream
[java.io.IOException] Server returned HTTP response code: 500 for URL: http://theserver:9080/ACS/servlet/ACS?command=read&version=2.3&docbaseid=003bdd&basepath=%2Fecontent%2Ftherepo%2Fcontent_storage_01%2F00003bdd&filepath=80%2F01%2F84%2F8a.zip&objectid=09003bdd800561c0&cacheid=dAAEAgA%3D%3DioQBgA%3D%3D&format=zip&pagenum=0&signature=FFFo9K0Z9DLIbbv2KUuy1GnqFWrFUrRyBh1WSN0PdGXdx5m70rPSZDTDRKDfUSvaF%2B7uBTaETDkIki5pypO9qvzdeMf0Tj2EIkXgFnzSXyXJ%2FRVxapafsfw%2FGeV%2FulWLDdRjScJu8V0AhzBvqRU4%2BebV1Q8cK5S6%2BV1DZoU2cD4%3D&servername=FRPAR-D2-DEVACS1&mode=1&timestamp=1439979449&length=3228176&mime_type=application%2Fx-zip-compressed&parallel_streaming=true&expire_delta=360

STACK TRACE:
org.cmis.ws.CmisException: Failed to get the content stream
[java.io.IOException] Server returned HTTP response code: 500 for URL: http://theserver:9080/ACS/servlet/ACS?command=read&version=2.3&docbaseid=003bdd&basepath=%2Fecontent%2Ftherepo%2Fcontent_storage_01%2F00003bdd&filepath=80%2F01%2F84%2F8a.zip&objectid=09003bdd800561c0&cacheid=dAAEAgA%3D%3DioQBgA%3D%3D&format=zip&pagenum=0&signature=FFFo9K0Z9DLIbbv2KUuy1GnqFWrFUrRyBh1WSN0PdGXdx5m70rPSZDTDRKDfUSvaF%2B7uBTaETDkIki5pypO9qvzdeMf0Tj2EIkXgFnzSXyXJ%2FRVxapafsfw%2FGeV%2FulWLDdRjScJu8V0AhzBvqRU4%2BebV1Q8cK5S6%2BV1DZoU2cD4%3D&servername=FRPAR-D2-DEVACS1&mode=1&timestamp=1439979449&length=3228176&mime_type=application%2Fx-zip-compressed&parallel_streaming=true&expire_delta=360
	at com.emc.documentum.fs.cmis.impl.dfs.utils.CmisExceptionFactory.create(CmisExceptionFactory.java:24)
	at com.emc.documentum.fs.cmis.impl.dfs.utils.CmisExceptionBuilder.build(CmisExceptionBuilder.java:31)
	at com.emc.documentum.fs.cmis.impl.dfs.action.GetContentStreamWithPropertiesAction.execute(GetContentStreamWithPropertiesAction.java:94)
	at com.emc.documentum.fs.cmis.impl.dfs.action.GetContentStreamWithPropertiesAction.execute(GetContentStreamWithPropertiesAction.java:59)
	at com.emc.documentum.fs.cmis.impl.filter.LinkedActionFilterChain.run(LinkedActionFilterChain.java:23)
	at com.emc.documentum.fs.cmis.impl.filter.RequestValidationFilter.doFilter(RequestValidationFilter.java:16)
	at com.emc.documentum.fs.cmis.impl.filter.LinkedActionFilterChain.run(LinkedActionFilterChain.java:21)
	at com.emc.documentum.fs.cmis.rs.impl.resource.ObjectMediaResource.get(ObjectMediaResource.java:67)
	at sun.reflect.GeneratedMethodAccessor93.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)
	at com.sun.jersey.server.impl.uri.rules.SubLocatorRule.accept(SubLocatorRule.java:134)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.SubLocatorRule.accept(SubLocatorRule.java:134)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.SubLocatorRule.accept(SubLocatorRule.java:134)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.SubLocatorRule.accept(SubLocatorRule.java:134)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1483)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1414)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1363)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1353)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:414)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.emc.documentum.fs.cmis.rs.impl.web.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:104)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://theserver:9080/ACS/servlet/ACS?command=read&version=2.3&docbaseid=003bdd&basepath=%2Fecontent%2Ftherepo%2Fcontent_storage_01%2F00003bdd&filepath=80%2F01%2F84%2F8a.zip&objectid=09003bdd800561c0&cacheid=dAAEAgA%3D%3DioQBgA%3D%3D&format=zip&pagenum=0&signature=FFFo9K0Z9DLIbbv2KUuy1GnqFWrFUrRyBh1WSN0PdGXdx5m70rPSZDTDRKDfUSvaF%2B7uBTaETDkIki5pypO9qvzdeMf0Tj2EIkXgFnzSXyXJ%2FRVxapafsfw%2FGeV%2FulWLDdRjScJu8V0AhzBvqRU4%2BebV1Q8cK5S6%2BV1DZoU2cD4%3D&servername=FRPAR-D2-DEVACS1&mode=1&timestamp=1439979449&length=3228176&mime_type=application%2Fx-zip-compressed&parallel_streaming=true&expire_delta=360
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at java.net.URL.openStream(URL.java:1037)
	at javax.activation.URLDataSource.getInputStream(URLDataSource.java:107)
	at com.emc.documentum.fs.cmis.impl.dfs.action.GetContentStreamWithPropertiesAction.getInputStream(GetContentStreamWithPropertiesAction.java:150)
	at com.emc.documentum.fs.cmis.impl.dfs.action.GetContentStreamWithPropertiesAction.getCmisContentStream(GetContentStreamWithPropertiesAction.java:119)
	at com.emc.documentum.fs.cmis.impl.dfs.action.GetContentStreamWithPropertiesAction.execute(GetContentStreamWithPropertiesAction.java:74)
	... 50 more
```

**Comment by nicolas-raoul** [comment]
Fixed, it was a Documentum configuration issue.

**Comment by PreetamKSur** [comment]
Hi Nicolas,

Can you please let me know what configuration you had fixed?
I am stuck with the same Problem.  Your help will be highly appreciated.

Thanks, 
Preetam

**Comment by vaibhav0014** [comment]
Hi Nicholas ,
Can you share how you fixed it.

**Comment by nicolas-raoul** [comment]
@PreetamKSur @vaibhav0014 Sorry for the delayed reply.

The Documentum server is hold by my customer, I don't have access to it, so I am not the one who fixed it, but here is what they wrote to me about how they fixed it (pardon my French):

> il ne s’agit pas d’un bug documentum mais d’erreur de téléchargement qui est liée à l’absence de contenu sur notre serveur de test. En effet, nous n’avons pas accès aux contenus mais uniquement les métadonnées. Pour vous débloquez, j’ai ajouté des contenus de test aux 4 documents qui se trouvent dans le répertoire.

Translation:

> It is not a Documentum bug but rather a download error which is linked to the absence of content on our test server. Indeed, we don't have access to the content pieces but only to the metadata pieces. To unstuck you from this problem, I have added test content pieces to the 4 documents that are in the directory.
