### ISSUE TITLE
Basic Auth fails with NemakiWare

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#611]
HTTP traffic seen by Wireshark:

```
GET /core/atom/bedroom HTTP/1.1
User-Agent: Apache Chemistry DotCMIS
Host: trial.nemakiware.com:8080
Connection: Keep-Alive

HTTP/1.1 500 Internal Server Error
Cache-Control: private, max-age=0
Server: Apache-Chemistry-OpenCMIS/0.13.0
Content-Type: text/html;charset=UTF-8
Transfer-Encoding: chunked
Date: Mon, 31 Aug 2015 07:02:25 GMT
Connection: closeb60
<html><head><title>Apache Chemistry OpenCMIS - runtime error</title><style><!--H1 {font-size:24px;line-height:normal;font-weight:bold;background-color:#f0f0f0
;color:#003366
;border-bottom:1px solid #3c78b5
;padding:2px;} BODY {font-family:Verdana,arial,sans-serif;color:black;font-size:14px;} HR {color:#3c78b5
;height:1px;}--></style></head><body><h1>HTTP Status 500 - <!--exception-->runtime<!--/exception--></h1><p><!--message-->[userName=null]Authentication failed<!--/message--></p><hr noshade='noshade'/><!--stacktrace--><pre>
org.apache.chemistry.opencmis.commons.exceptions.CmisProxyAuthenticationException: [userName=null]Authentication failed
.at jp.aegif.nemaki.cmis.factory.CmisServiceFactory.getService(CmisServiceFactory.java:78)
.at org.apache.chemistry.opencmis.server.impl.atompub.CmisAtomPubServlet.dispatch(CmisAtomPubServlet.java:230)
.at org.apache.chemistry.opencmis.server.impl.atompub.CmisAtomPubServlet.service(CmisAtomPubServlet.java:193)
.at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
.at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
.at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
.at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
.at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
.at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
.at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
.at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
.at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
.at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
.at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
.at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
.at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
.at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
.at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
.at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
.at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1526)
.at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1482)
.at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
.at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
.at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
.at java.lang.Thread.run(Thread.java:745)</pre><!--/stacktrace--><hr noshade='noshade'/></body></html>
0 
```

**Comment by nicolas-raoul** [comment]
https://github.com/OpenDataSpace/chemistry-dotcmis/commit/73309c719956b75804b92d8f76f866fde0a4946b#commitcomment-12993159
