### ISSUE TITLE
Stuck on file deleted locally and remotely

### ISSUE THREAD

**Issue by icaptnbob** [aegif/CmisSync#647]
CMIS Sync keeps synchronising, stuck in this loop, not able to find a file on the remote, but it's deleted locally.
This may have happened when a file was deleted on the server and before CMIS Sync could pick up the change, it was deleted locally as well.

2015-12-16 14:33:36,027 [4] DEBUG CmisSync.Lib.SyncItem [(null)] - File.Exists(C:\Data\Alfresco_CMIS_Sync\business-services-reports\EE automated reports\TEST_2015-12-01_00-24.rar) = False
2015-12-16 14:33:36,027 [4] INFO  CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - CmisSync Warning: You have deleted file C:\Data\Alfresco_CMIS_Sync\business-services-reports\EE automated reports\TEST_2015-12-01_00-24.rar
CmisSync will now delete it from the server. If you actually did not delete this file, please report a bug at CmisSync@aegif.jp
2015-12-16 14:33:36,027 [4] DEBUG CmisSync.StatusIconController [(null)] - StatusIconController OnSyncing
2015-12-16 14:33:36,027 [4] INFO  CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Removing locally deleted file on server: /Sites/business-services-reports/documentLibrary/E&E automated reports\TEST_2015-12-01_00-24.rar
2015-12-16 14:33:36,840 [4] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not access remote object: TEST_2015-12-01_00-24.rar
DotCMIS.Exceptions.CmisRuntimeException: Unauthorized
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Delete(UrlBuilder url)
   at DotCMIS.Binding.AtomPub.ObjectService.DeleteObject(String repositoryId, String objectId, Nullable`1 allVersions, IExtensionsData extension)
   at DotCMIS.Client.Impl.Session.Delete(IObjectId objectId, Boolean allVersions)
   at DotCMIS.Client.Impl.AbstractCmisObject.Delete(Boolean allVersions)
   at DotCMIS.Client.Impl.Document.DeleteAllVersions()
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlRemoteDocument(IDocument remoteDocument, String remotePath, String localFolder, IList`1 remoteFiles)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.CrawlRemote(IFolder remoteFolder, String remotePath, String localFolder, IList`1 remoteFiles, IList`1 remoteFolders)

**Comment by icaptnbob** [comment]
User only had Collaborator permissions, couldn't delete the file. Solved by changing to Manager and the file delete completed, error gone now.
