### ISSUE TITLE
Could not sync "organization": Bad Request

### ISSUE THREAD

**Issue by knucie** [aegif/CmisSync#652]
Dear All,

I managed to connect to my organization SP2013 server, however once CmisSync launches, i get an error _Could not sync "2ks": Bad Request_. 

Below is the log file. 

Does anyone have any ideas on where the problem lies? Many thanks.

2016-02-05 08:53:29,014 [1] INFO  CmisSync.Program [(null)] - Starting. Version: 2.6.5.0
2016-02-05 08:53:29,032 [1] INFO  CmisSync.Lib.FolderLock [(null)] - Creating folder lock file: C:\Users\Ignas\CmisSync
2016-02-05 08:53:29,046 [1] DEBUG CmisSync.SetupController [(null)] - SetupController - Entering constructor.
2016-02-05 08:53:29,046 [1] DEBUG CmisSync.SetupController [(null)] - SetupController - Exiting constructor.
2016-02-05 08:53:29,088 [1] DEBUG CmisSync.Setup [(null)] - Entering constructor.
2016-02-05 08:53:29,089 [1] DEBUG CmisSync.Setup [(null)] - Exiting constructor.
2016-02-05 08:53:29,103 [5] INFO  CmisSync.Lib.RepoBase [(null)] - Repo 2ks - Set poll interval to 5000ms
2016-02-05 08:53:29,104 [5] INFO  CmisSync.Lib.Sync.CmisRepo [(null)] - CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder
2016-02-05 08:53:29,106 [5] INFO  CmisSync.Lib.RepoBase [(null)] - Repo 2ks sync launch at startup
2016-02-05 08:53:29,108 [3] INFO  CmisSync.Lib.RepoBase [(null)] - Full Sync Started: C:\Users\Ignas\CmisSync\2ks
2016-02-05 08:53:33,140 [3] INFO  CmisSync.Lib.RepoBase [(null)] - Sync Error: CmisSync.Lib.Cmis.BaseException, Bad Request
2016-02-05 08:53:33,141 [3] ERROR CmisSync.StatusIconController [(null)] - Error syncing '2ks': Bad Request
CmisSync.Lib.Cmis.BaseException: Bad Request ---> DotCMIS.Exceptions.CmisInvalidArgumentException: Bad Request
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Read(UrlBuilder url)
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.GetRepositoriesInternal(String repositoryId)
   at DotCMIS.Binding.AtomPub.RepositoryService.GetRepositoryInfo(String repositoryId, IExtensionsData extension)
   at DotCMIS.Binding.Impl.BindingRepositoryService.GetRepositoryInfo(String repositoryId, IExtensionsData extension)
   at DotCMIS.Client.Impl.Session.Connect()
   at DotCMIS.Client.Impl.SessionFactory.CreateSession(IDictionary`2 parameters, IObjectFactory objectFactory, IAuthenticationProvider authenticationProvider, ICache cache)
   at DotCMIS.Client.Impl.SessionFactory.CreateSession(IDictionary`2 parameters)
   at CmisSync.Auth.Auth.GetCmisSession(String url, String user, String password, String repositoryId)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.Connect()
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.Sync(Boolean syncFull)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.<>c__DisplayClass6.<.ctor>b__4(Object o, DoWorkEventArgs args)
   --- End of inner exception stack trace ---
2016-02-05 08:53:33,156 [3] INFO  CmisSync.Lib.RepoBase [(null)] - Full Sync Complete: C:\Users\Ignas\CmisSync\2ks

**Comment by nicolas-raoul** [comment]
Do you manage to see and download all files correctly with CMIS Workbench?
http://chemistry.apache.org/java/developing/tools/dev-tools-workbench.html
