### ISSUE TITLE
cant sync cmissync  from desktop to server

### ISSUE THREAD

**Issue by zuppudy** [aegif/CmisSync#663]
when I am uploading from desktop cant sync.But i was able to see from server side
here the log error
_2016-03-29_ 10:44:25,292 [13] DEBUG CmisSync.Lib.SyncItem [(null)] - File.Exists(C:\Users\Amerisoftpro\CmisSync\staging.mycloudbin.com\kumar\OpenCMIS Server Development Guide (1).pdf) = True
2016-03-29 10:44:25,307 [13] INFO  CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Uploading file absent on repository: C:\Users\Amerisoftpro\CmisSync\staging.mycloudbin.com\kumar\atom11
2016-03-29 10:44:25,307 [13] DEBUG CmisSync.StatusIconController [(null)] - StatusIconController OnSyncing
2016-03-29 10:44:25,323 [13] INFO  CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Uploading: C:\Users\Amerisoftpro\CmisSync\staging.mycloudbin.com\kumar\atom11
2016-03-29 10:44:25,323 [13] DEBUG CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Uploading: C:\Users\Amerisoftpro\CmisSync\staging.mycloudbin.com\kumar\atom11 as //atom11
2016-03-29 10:44:25,338 [13] _ERROR C_misSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not upload file: C:\Users\Amerisoftpro\CmisSync\staging.mycloudbin.com\kumar\atom11
DotCMIS.Exceptions.CmisRuntimeException: Length Required
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Post(UrlBuilder url, String contentType, Output writer)
   at DotCMIS.Binding.AtomPub.ObjectService.CreateDocument(String repositoryId, IProperties properties, String folderId, IContentStream contentStream, Nullable`1 versioningState, IList`1 policies, IAcl addAces, IAcl removeAces, IExtensionsData extension)
   at DotCMIS.Client.Impl.Session.CreateDocument(IDictionary`2 properties, IObjectId folderId, IContentStream contentStream, Nullable`1 versioningState, IList`1 policies, IList`1 addAces, IList`1 removeAces)
   at DotCMIS.Client.Impl.Folder.CreateDocument(IDictionary`2 properties, IContentStream contentStream, Nullable`1 versioningState, IList`1 policies, IList`1 addAces, IList`1 removeAces, IOperationContext context)
   at DotCMIS.Client.Impl.Folder.CreateDocument(IDictionary`2 properties, IContentStream contentStream, Nullable`1 versioningState)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.UploadFile(String filePath, IFolder remoteFolder)
2016-03-29 10:44:25,354 [13] INFO  CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Uploading file absent on repository: C:\Users\Amerisoftpro\CmisSync\staging.mycloudbin.com\kumar\cmis server.txt
2016-03-29 10:44:25,354 [13] DEBUG CmisSync.StatusIconController [(null)] - StatusIconController OnSyncing
2016-03-29 10:44:25,354 [13] INFO  CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Uploading: C:\Users\Amerisoftpro\CmisSync\staging.mycloudbin.com\kumar\cmis server.txt
2016-03-29 10:44:25,354 [13] DEBUG CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Uploading: C:\Users\Amerisoftpro\CmisSync\staging.mycloudbin.com\kumar\cmis server.txt as //cmis server.txt
2016-03-29 10:44:25,407 [13] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not upload file: C:\Users\Amerisoftpro\CmisSync\staging.mycloudbin.com\kumar\cmis server.txt
DotCMIS.Exceptions.CmisRuntimeException: Length Required

**Comment by nicolas-raoul** [comment]
Fixed by disabling chunked upload for this particular customer.
