### ISSUE TITLE
Conflicting file never downloaded

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#680]
CmisSync was recently modified to upload before downloading. This leads to a situation where upload fails and the conflicting document is not downloaded:

```
2016-05-24 15:52:32,937 [14] DEBUG CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Uploading: C:\alternativeCmisSyncTarget\New Text Document.txt as /Sites/swsdp/documentLibrary/Presentations/New Text Document.txt
2016-05-24 15:52:33,061 [14] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not upload file: C:\alternativeCmisSyncTarget\New Text Document.txt
DotCMIS.Exceptions.CmisConstraintException: Conflict
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Post(UrlBuilder url, String contentType, Output writer) in C:\Users\win7pro32bit\Documents\ASaasDriveClient\Extras\OpenDataSpaceDotCMIS\DotCMIS\binding\atompub\atompub.cs:line 480
   at DotCMIS.Binding.AtomPub.ObjectService.CreateDocument(String repositoryId, IProperties properties, String folderId, IContentStream contentStream, Nullable`1 versioningState, IList`1 policies, IAcl addAces, IAcl removeAces, IExtensionsData extension) in C:\Users\win7pro32bit\Documents\ASaasDriveClient\Extras\OpenDataSpaceDotCMIS\DotCMIS\binding\atompub\atompub.cs:line 1587
   at DotCMIS.Client.Impl.Session.CreateDocument(IDictionary`2 properties, IObjectId folderId, IContentStream contentStream, Nullable`1 versioningState, IList`1 policies, IList`1 addAces, IList`1 removeAces) in C:\Users\win7pro32bit\Documents\ASaasDriveClient\Extras\OpenDataSpaceDotCMIS\DotCMIS\client\client-impl.cs:line 783
   at DotCMIS.Client.Impl.Folder.CreateDocument(IDictionary`2 properties, IContentStream contentStream, Nullable`1 versioningState, IList`1 policies, IList`1 addAces, IList`1 removeAces, IOperationContext context) in C:\Users\win7pro32bit\Documents\ASaasDriveClient\Extras\OpenDataSpaceDotCMIS\DotCMIS\client\client-objects.cs:line 1030
   at DotCMIS.Client.Impl.Folder.CreateDocument(IDictionary`2 properties, IContentStream contentStream, Nullable`1 versioningState) in C:\Users\win7pro32bit\Documents\ASaasDriveClient\Extras\OpenDataSpaceDotCMIS\DotCMIS\client\client-objects.cs:line 1358
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.UploadFile(String filePath, IFolder remoteFolder) in C:\Users\win7pro32bit\Documents\ASaasDriveClient\CmisSync.Lib\Sync\SynchronizedFolder.cs:line 1094
```

**Comment by nicolas-raoul** [comment]
Tried again and could not reproduce.

**Comment by nicolas-raoul** [comment]
Actually, after this error message the normal conflict popup appears.
