### ISSUE TITLE
ArgumentNullException: Value cannot be null. Parameter name: stream

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#684]
1. Delete a lot of folders on local filesystem
2. Delete them at the same time on the server

```
2016-05-25 18:54:41,757 [16] INFO  CmisSync.Lib.RepoBase [(null)] - Sync Error: CmisSync.Lib.Cmis.BaseException, Value cannot be null.
Parameter name: stream
2016-05-25 18:54:41,757 [16] ERROR CmisSync.StatusIconController [(null)] - Error syncing '<server>\bedroom': Value cannot be null.
Parameter name: stream
CmisSync.Lib.Cmis.BaseException: Value cannot be null.
Parameter name: stream ---> System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding)
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Read(UrlBuilder url) in C:\Users\win7pro32bit\Documents\ASaasDriveClient\Extras\OpenDataSpaceDotCMIS\DotCMIS\binding\atompub\atompub.cs:line 445
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.GetObjectInternal(String repositoryId, IdentifierType idOrPath, String objectIdOrPath, Nullable`1 returnVersion, String filter, Nullable`1 includeAllowableActions, Nullable`1 includeRelationships, String renditionFilter, Nullable`1 includePolicyIds, Nullable`1 includeAcl, IExtensionsData extension) in C:\Users\win7pro32bit\Documents\ASaasDriveClient\Extras\OpenDataSpaceDotCMIS\DotCMIS\binding\atompub\atompub.cs:line 828
   at DotCMIS.Binding.AtomPub.ObjectService.GetObjectByPath(String repositoryId, String path, String filter, Nullable`1 includeAllowableActions, Nullable`1 includeRelationships, String renditionFilter, Nullable`1 includePolicyIds, Nullable`1 includeAcl, IExtensionsData extension) in C:\Users\win7pro32bit\Documents\ASaasDriveClient\Extras\OpenDataSpaceDotCMIS\DotCMIS\binding\atompub\atompub.cs:line 1830
   at DotCMIS.Client.Impl.Session.GetObjectByPath(String path, IOperationContext context) in C:\Users\win7pro32bit\Documents\ASaasDriveClient\Extras\OpenDataSpaceDotCMIS\DotCMIS\client\client-impl.cs:line 570
   at DotCMIS.Client.Impl.Session.GetObjectByPath(String path) in C:\Users\win7pro32bit\Documents\ASaasDriveClient\Extras\OpenDataSpaceDotCMIS\DotCMIS\client\client-impl.cs:line 543
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.ApplyLocalChanges(String rootFolder) in C:\Users\win7pro32bit\Documents\ASaasDriveClient\CmisSync.Lib\Sync\LocalComparisonStrategy.cs:line 75
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.Sync(Boolean syncFull) in C:\Users\win7pro32bit\Documents\ASaasDriveClient\CmisSync.Lib\Sync\SynchronizedFolder.cs:line 431
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.<>c__DisplayClass6.<.ctor>b__4(Object o, DoWorkEventArgs args) in C:\Users\win7pro32bit\Documents\ASaasDriveClient\CmisSync.Lib\Sync\SynchronizedFolder.cs:line 186
   --- End of inner exception stack trace ---
```

Workaround: Stop, delete .cmissync file, restart

TODO: Add exception handling in LocalComparizonStrategy. In case of failure, run full sync.

**Comment by nicolas-raoul** [comment]
Fixed
