### ISSUE TITLE
No synchroniaation between CmisSync and sharepoint 2010

### ISSUE THREAD

**Issue by MBD67** [aegif/CmisSync#703]
Hi, I don't know why the synchronisation doesn't work. the installation on the server is ok, the feature is activated, the folder is well created on local...What it doesn't found ?
Can you help me please? thanks

2016-06-28 09:47:19,416 [14] INFO  CmisSync.Lib.RepoBase [(null)] - Full Sync Started: C:\Users\C526747\CmisSync\Gdoc\Espace de référence\gdoc\Espace de référence
2016-06-28 09:47:19,770 [14] INFO  CmisSync.Lib.RepoBase [(null)] - Sync Error: CmisSync.Lib.Cmis.BaseException, Not Found
2016-06-28 09:47:19,770 [14] ERROR CmisSync.StatusIconController [(null)] - Error syncing 'gdoc\Espace de référence': Not Found
CmisSync.Lib.Cmis.BaseException: Not Found ---> DotCMIS.Exceptions.CmisObjectNotFoundException: Not Found
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Read(UrlBuilder url)
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.GetObjectInternal(String repositoryId, IdentifierType idOrPath, String objectIdOrPath, Nullable`1 returnVersion, String filter, Nullable`1 includeAllowableActions, Nullable`1 includeRelationships, String renditionFilter, Nullable`1 includePolicyIds, Nullable`1 includeAcl, IExtensionsData extension)
   at DotCMIS.Binding.AtomPub.ObjectService.GetObjectByPath(String repositoryId, String path, String filter, Nullable`1 includeAllowableActions, Nullable`1 includeRelationships, String renditionFilter, Nullable`1 includePolicyIds, Nullable`1 includeAcl, IExtensionsData extension)
   at DotCMIS.Client.Impl.Session.GetObjectByPath(String path, IOperationContext context)
   at DotCMIS.Client.Impl.Session.GetObjectByPath(String path)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.Sync(Boolean syncFull)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.<>c__DisplayClass6.<.ctor>b__4(Object o, DoWorkEventArgs args)

**Comment by nicolas-raoul** [comment]
Is it SharePoint Foundation maybe? Are you using SSO?
Could you please email me at CmisSync@aegif.jp? Merci !

**Comment by MBD67** [comment]
Hi,

Thank you for your contact.
We are using SharePoint 2010 enterprise SP1 at the moment and SP2 after
this week.
Yes, we are on SSO but I specified my password to see the Library I want to
synchronize.



2016-06-30 16:16 GMT+02:00 Nicolas Raoul <notifications@github.com>:

**Comment by nicolas-raoul** [comment]
The free CmisSync only has Basic Authentication, which your server probably refuses. For SSO you will need CmisSync Business. Please email us at CmisSync@aegif.jp, we can send you a trial version. Thank you!

**Comment by MBD67** [comment]
Hi,

did you have some track for us ?
Thank you


Nadine

2016-06-30 17:05 GMT+02:00 Nadine BOEHMANN <nboehmann@gmail.com>:

**Comment by MBD67** [comment]
Hi,
can you support us please ? Thank you.
best regards .
Nadine

2016-07-06 10:57 GMT+02:00 Nadine BOEHMANN <nboehmann@gmail.com>:
