### ISSUE TITLE
Property cmis:contentStreamFileName is non orderable and can not be used in ORDER BY clause

### ISSUE THREAD

**Issue by nicolas-raoul** [aegif/CmisSync#724]
Request sent by CmisSync:
```
http://server:443/emc-cmis/resources/testenv/children?id=0c0f095980000104&orderBy=cmis:contentStreamFileName&includeAllowableActions=true&includeRelationships=none&includePathSegment=true&maxItems=2147483647&skipCount=0
```
Response received from Documentum 7.3:
```
Headers:
2016-09-01 16:27:41,011 [11] WARN  DotCMIS.Binding.AtomPub.AbstractAtomPubService [(null)] - - Transfer-Encoding: chunked
2016-09-01 16:27:42,503 [11] WARN  DotCMIS.Binding.AtomPub.AbstractAtomPubService [(null)] - - Connection: close
2016-09-01 16:27:43,375 [11] WARN  DotCMIS.Binding.AtomPub.AbstractAtomPubService [(null)] - - Cache-Control: private, max-age=0
2016-09-01 16:27:44,516 [11] WARN  DotCMIS.Binding.AtomPub.AbstractAtomPubService [(null)] - - Content-Type: text/html;charset=UTF-8
2016-09-01 16:27:45,685 [11] WARN  DotCMIS.Binding.AtomPub.AbstractAtomPubService [(null)] - - Date: Thu, 01 Sep 2016 07:27:24 GMT
2016-09-01 16:27:47,100 [11] WARN  DotCMIS.Binding.AtomPub.AbstractAtomPubService [(null)] - - Server: Apache-Chemistry-OpenCMIS/0.13.0
2016-09-01 16:27:48,033 [11] WARN  DotCMIS.Binding.AtomPub.AbstractAtomPubService [(null)] - Error content:
2016-09-01 16:27:48,938 [11] WARN  DotCMIS.Binding.AtomPub.AbstractAtomPubService [(null)] - <html><head><title>Apache Chemistry OpenCMIS - runtime error</title><style><!--H1 {font-size:24px;line-height:normal;font-weight:bold;background-color:#f0f0f0;color:#003366;border-bottom:1px solid #3c78b5;padding:2px;} BODY {font-family:Verdana,arial,sans-serif;color:black;font-size:14px;} HR {color:#3c78b5;height:1px;}--></style></head><body><h1>HTTP Status 500 - <!--exception-->runtime<!--/exception--></h1><p><!--message-->Failed to get children of folder with id - 'null' due to following exception: Property cmis:contentStreamFileName is non orderable and can not be used in ORDER BY clause<!--/message--></p><hr noshade='noshade'/><!--stacktrace--><pre>
org.apache.chemistry.opencmis.commons.exceptions.CmisRuntimeException: Failed to get children of folder with id - 'null' due to following exception: Property cmis:contentStreamFileName is non orderable and can not be used in ORDER BY clause
	at com.emc.documentum.fs.cmis.impl.cmisoperations.impl.AbstractCmisOperationHandler.handleException(AbstractCmisOperationHandler.java:99)
	at com.emc.documentum.fs.cmis.impl.cmisoperations.impl.AbstractCmisOperationHandler.execute(AbstractCmisOperationHandler.java:29)
	at com.emc.documentum.fs.cmis.EmcDocumentumCmisService.getChildren(EmcDocumentumCmisService.java:111)
	at org.apache.chemistry.opencmis.server.support.wrapper.ConformanceCmisServiceWrapper.getChildren(ConformanceCmisServiceWrapper.java:631)
	at org.apache.chemistry.opencmis.server.impl.atompub.NavigationService$GetChildren.serve(NavigationService.java:78)
	at org.apache.chemistry.opencmis.server.shared.Dispatcher.dispatch(Dispatcher.java:92)
	at org.apache.chemistry.opencmis.server.impl.atompub.CmisAtomPubServlet.dispatch(CmisAtomPubServlet.java:244)
	at org.apache.chemistry.opencmis.server.impl.atompub.CmisAtomPubServlet.service(CmisAtomPubServlet.java:193)
	at com.emc.documentum.fs.cmis.impl.atompub.servlet.EmcCmisAtomPubServlet.service(EmcCmisAtomPubServlet.java:30)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at com.emc.documentum.fs.cmis.impl.atompub.web.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:32)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2503)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.cmis.ws.CmisException: Property cmis:contentStreamFileName is non orderable and can not be used in ORDER BY clause
	at com.emc.documentum.fs.cmis.impl.dfs.utils.CmisExceptionFactory.create(CmisExceptionFactory.java:24)
	at com.emc.documentum.fs.cmis.impl.dfs.utils.CmisExceptionBuilder.build(CmisExceptionBuilder.java:31)
	at com.emc.documentum.fs.cmis.impl.dfs.utils.orderby.OrderBy.getPropertyDef(OrderBy.java:73)
	at com.emc.documentum.fs.cmis.impl.dfs.utils.orderby.OrderBy.getLocalName(OrderBy.java:56)
	at com.emc.documentum.fs.cmis.impl.dfs.utils.orderby.OrderBy.asDFS(OrderBy.java:36)
	at com.emc.documentum.fs.cmis.impl.query.DQLBuilder.order(DQLBuilder.java:63)
	at com.emc.documentum.fs.cmis.impl.dfs.action.query.FolderChildrenQuery.folderChildren(FolderChildrenQuery.java:26)
	at com.emc.documentum.fs.cmis.impl.dfs.action.query.FolderChildrenQuery.query(FolderChildrenQuery.java:20)
	at com.emc.documentum.fs.cmis.impl.dfs.action.query.FolderChildrenQuery.compose(FolderChildrenQuery.java:12)
	at com.emc.documentum.fs.cmis.impl.dfs.action.GetChildrenAction.queryChildren(GetChildrenAction.java:149)
	at com.emc.documentum.fs.cmis.impl.dfs.action.GetChildrenAction.execute(GetChildrenAction.java:50)
	at com.emc.documentum.fs.cmis.impl.dfs.action.GetChildrenAction.execute(GetChildrenAction.java:44)
	at com.emc.documentum.fs.cmis.impl.filter.LinkedActionFilterChain.run(LinkedActionFilterChain.java:23)
	at com.emc.documentum.fs.cmis.impl.filter.RequestValidationFilter.doFilter(RequestValidationFilter.java:16)
	at com.emc.documentum.fs.cmis.impl.filter.LinkedActionFilterChain.run(LinkedActionFilterChain.java:21)
	at com.emc.documentum.fs.cmis.impl.filter.AuthenticationFilter.doFilter(AuthenticationFilter.java:19)
	at com.emc.documentum.fs.cmis.impl.filter.LinkedActionFilterChain.run(LinkedActionFilterChain.java:21)
	at com.emc.documentum.fs.cmis.impl.filter.AnonymousAccessFilter.doFilter(AnonymousAccessFilter.java:19)
	at com.emc.documentum.fs.cmis.impl.filter.LinkedActionFilterChain.run(LinkedActionFilterChain.java:21)
	at com.emc.documentum.fs.cmis.impl.cmisoperations.impl.AbstractCmisOperationHandler.executeAction(AbstractCmisOperationHandler.java:50)
	at com.emc.documentum.fs.cmis.impl.cmisoperations.impl.GetChildrenOperationHandler.generateResponse(GetChildrenOperationHandler.java:43)
	at com.emc.documentum.fs.cmis.impl.cmisoperations.impl.GetChildrenOperationHandler.generateResponse(GetChildrenOperationHandler.java:16)
	at com.emc.documentum.fs.cmis.impl.cmisoperations.impl.AbstractCmisOperationHandler.execute(AbstractCmisOperationHandler.java:23)
	... 32 more

</pre><!--/stacktrace--><hr noshade='noshade'/></body></html>
```

**Comment by nicolas-raoul** [comment]
Fixed by e3bb8c75ce7c2170dc5fc6ee9b7f8b9e31055594
