### ISSUE TITLE
ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder

### ISSUE THREAD

**Issue by EmilianoGomez007** [aegif/CmisSync#734]
```
2017-01-10 22:01:51,874 [3] ERROR CmisSync.Lib.Sync.CmisRepo+SynchronizedFolder [(null)] - Could not upload file: Q:\ACCIDENTES PERSONALES\ENDOSOS  ACC PERSONALES\ENDOSOS CLAUSULAS DE COASEGURO\5705229.doc
DotCMIS.Exceptions.CmisConnectionException: Cannot access https://formatosdrp.lapositiva.com.pe:8443/alfresco/api/-default-/public/cmis/versions/1.1/atom/children?id=1a5a0483-55e8-4508-a984-3ab739509e29: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DotCMIS.Binding.Impl.HttpUtils.Response.ExtractHeader()
   at DotCMIS.Binding.Impl.HttpUtils.Response..ctor(WebException exception)
   at DotCMIS.Binding.Impl.HttpUtils.Invoke(UrlBuilder url, String method, String contentType, Output writer, BindingSession session, Nullable`1 offset, Nullable`1 length, IDictionary`2 headers)
   --- End of inner exception stack trace ---
   at DotCMIS.Binding.Impl.HttpUtils.Invoke(UrlBuilder url, String method, String contentType, Output writer, BindingSession session, Nullable`1 offset, Nullable`1 length, IDictionary`2 headers)
   at DotCMIS.Binding.Impl.HttpUtils.InvokePOST(UrlBuilder url, String contentType, Output writer, BindingSession session)
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Post(UrlBuilder url, String contentType, Output writer)
   at DotCMIS.Binding.AtomPub.ObjectService.CreateDocument(String repositoryId, IProperties properties, String folderId, IContentStream contentStream, Nullable`1 versioningState, IList`1 policies, IAcl addAces, IAcl removeAces, IExtensionsData extension)
   at DotCMIS.Client.Impl.Session.CreateDocument(IDictionary`2 properties, IObjectId folderId, IContentStream contentStream, Nullable`1 versioningState, IList`1 policies, IList`1 addAces, IList`1 removeAces)
   at DotCMIS.Client.Impl.Folder.CreateDocument(IDictionary`2 properties, IContentStream contentStream, Nullable`1 versioningState, IList`1 policies, IList`1 addAces, IList`1 removeAces, IOperationContext context)
   at DotCMIS.Client.Impl.Folder.CreateDocument(IDictionary`2 properties, IContentStream contentStream, Nullable`1 versioningState)
   at CmisSync.Lib.Sync.CmisRepo.SynchronizedFolder.UploadFile(String filePath, IFolder remoteFolder)
```

**Comment by nicolas-raoul** [comment]
The server was not accessible.
Please make sure your server is running, it should work.
Please reopen if the problem persists, thanks!
