### ISSUE TITLE
not able to login on a particular address.

### ISSUE THREAD

**Issue by monicakumari** [aegif/CmisSync#760]
Hello,
I am getting the following exception, while trying to add a remote folder on a particular address, It is not letting me continue.

`2018-04-16 18:12:35,873 [1] INFO  CmisSync.Program [(null)] - Starting. Version: 2.11.3.0
2018-04-16 18:12:35,904 [1] INFO  CmisSync.Lib.FolderLock [(null)] - Creating folder lock file: C:\Users\monica2\CmisSync
2018-04-16 18:12:35,920 [1] DEBUG CmisSync.SetupController [(null)] - SetupController - Entering constructor.
2018-04-16 18:12:35,920 [1] DEBUG CmisSync.SetupController [(null)] - SetupController - Exiting constructor.
2018-04-16 18:12:35,983 [1] DEBUG CmisSync.Setup [(null)] - Entering constructor.
2018-04-16 18:12:35,983 [1] DEBUG CmisSync.Setup [(null)] - Exiting constructor.
2018-04-16 18:12:43,748 [1] DEBUG CmisSync.Setup [(null)] - Entering ChangePageEvent.
2018-04-16 18:12:43,779 [1] DEBUG CmisSync.Setup [(null)] - Exiting ChangePageEvent.
2018-04-16 18:12:43,795 [1] DEBUG CmisSync.Setup [(null)] - Entering ShowWindowEvent.
2018-04-16 18:12:43,873 [1] DEBUG CmisSync.Setup [(null)] - Exiting ShowWindowEvent.
2018-04-16 18:13:03,615 [5] INFO  CmisSync.Auth.Authentication [(null)] - Your password is not obfuscated.
2018-04-16 18:13:03,661 [5] DEBUG DotCMIS.Binding.Impl.HttpUtils [(null)] - Timeout=3600000ms ReadWriteTimeout=21600000ms
2018-04-16 18:13:04,655 [5] ERROR CmisSync.Lib.Cmis.CmisUtils [(null)] - No CMIS server at this address, or no connection. 
DotCMIS.Exceptions.CmisConnectionException: Parsing exception! ---> System.Xml.XmlException: Reference to undeclared entity 'raquo'. Line 9, position 47.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(String name, Boolean isInAttributeValue, Boolean pushFakeEntityIfNullResolver, Int32 entityStartLinePos)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.SkipPartialTextValue()
   at System.Xml.XmlTextReaderImpl.Read()
   at DotCMIS.Binding.AtomPub.AtomPubParser.Parse()
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Parse[T](Stream stream)
   --- End of inner exception stack trace ---
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Parse[T](Stream stream)
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.GetRepositoriesInternal(String repositoryId)
   at DotCMIS.Binding.AtomPub.RepositoryService.GetRepositoryInfos(IExtensionsData extension)
   at DotCMIS.Binding.Impl.BindingRepositoryService.GetRepositoryInfos(IExtensionsData extension)
   at DotCMIS.Client.Impl.SessionFactory.GetRepositories(IDictionary`2 parameters, IObjectFactory objectFactory, IAuthenticationProvider authenticationProvider, ICache cache)
   at DotCMIS.Client.Impl.SessionFactory.GetRepositories(IDictionary`2 parameters)
   at CmisSync.Auth.Authentication.GetCmisRepositories(Uri url, String user, String obfuscatedPassword)
   at CmisSync.Lib.Cmis.CmisUtils.GetRepositories(ServerCredentials credentials)
2018-04-16 18:13:04,655 [5] INFO  CmisSync.Lib.Cmis.CmisUtils [(null)] - Sync | Trying with https://eisenvault.net/alfresco/api/-default-/public/cmis/versions/1.1/atom
2018-04-16 18:13:04,670 [5] INFO  CmisSync.Auth.Authentication [(null)] - Your password is not obfuscated.
2018-04-16 18:13:04,670 [5] DEBUG DotCMIS.Binding.Impl.HttpUtils [(null)] - Timeout=3600000ms ReadWriteTimeout=21600000ms
`

don't know, what is the issue. I am entering correct credentials.

Thanks.

**Comment by nicolas-raoul** [comment]
Hello @monicakumari 
Thanks for your feedback!
Does [CMIS Workbench](https://superuser.com/questions/990835/how-to-install-and-use-cmis-workbench) show your files successfully?

**Comment by monicakumari** [comment]
Thanks for your reply nick. Yes. A folder a created named cmissync. But its showing me the above exception whilte trying to add remote folder. This issue is with that particular address. On othere addresses, its working fine. 
Thanks.

**Comment by nicolas-raoul** [comment]
Please post a screenshot of CMIS Workbench displaying your folder, thanks!

**Comment by monicakumari** [comment]
Its not loading repositories. 
![capture](https://user-images.githubusercontent.com/26789477/38865545-b1254b38-425b-11e8-9ccf-9ffa143733b5.PNG)

**Comment by monicakumari** [comment]
This is the debug logs I got from cmissync folder.


`2018-04-17 11:01:17,890 [6] INFO  CmisSync.Auth.Authentication [(null)] - Your password is not obfuscated.
2018-04-17 11:01:17,921 [6] DEBUG DotCMIS.Binding.Impl.HttpUtils [(null)] - Timeout=3600000ms ReadWriteTimeout=21600000ms
2018-04-17 11:01:18,706 [6] ERROR CmisSync.Lib.Cmis.CmisUtils [(null)] - No CMIS server at this address, or no connection. 
DotCMIS.Exceptions.CmisConnectionException: Parsing exception! ---> System.Xml.XmlException: Reference to undeclared entity 'raquo'. Line 9, position 47.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleGeneralEntityReference(String name, Boolean isInAttributeValue, Boolean pushFakeEntityIfNullResolver, Int32 entityStartLinePos)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   at System.Xml.XmlTextReaderImpl.SkipPartialTextValue()
   at System.Xml.XmlTextReaderImpl.Read()
   at DotCMIS.Binding.AtomPub.AtomPubParser.Parse()
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Parse[T](Stream stream)
   --- End of inner exception stack trace ---
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.Parse[T](Stream stream)
   at DotCMIS.Binding.AtomPub.AbstractAtomPubService.GetRepositoriesInternal(String repositoryId)
   at DotCMIS.Binding.AtomPub.RepositoryService.GetRepositoryInfos(IExtensionsData extension)
   at DotCMIS.Binding.Impl.BindingRepositoryService.GetRepositoryInfos(IExtensionsData extension)
   at DotCMIS.Client.Impl.SessionFactory.GetRepositories(IDictionary`2 parameters, IObjectFactory objectFactory, IAuthenticationProvider authenticationProvider, ICache cache)
   at DotCMIS.Client.Impl.SessionFactory.GetRepositories(IDictionary`2 parameters)
   at CmisSync.Auth.Authentication.GetCmisRepositories(Uri url, String user, String obfuscatedPassword)
   at CmisSync.Lib.Cmis.CmisUtils.GetRepositories(ServerCredentials credentials)
2018-04-17 11:01:18,711 [6] INFO  CmisSync.Lib.Cmis.CmisUtils [(null)] - Sync | Trying with https://www.eisenvault.net/alfresco/api/-default-/public/cmis/versions/1.1/atom
2018-04-17 11:01:18,713 [6] INFO  CmisSync.Auth.Authentication [(null)] - Your password is not obfuscated.
2018-04-17 11:01:18,713 [6] DEBUG DotCMIS.Binding.Impl.HttpUtils [(null)] - Timeout=3600000ms ReadWriteTimeout=21600000ms
`

**Comment by nicolas-raoul** [comment]
You must resolve the problem using CMIS Workbench before even trying with CmisSync.

Most probably your URL is not a valid CMIS URL. Please ask that website's administrator whether it supports the CMIS protocol or not.

Cheers!
Nicolas

**Comment by monicakumari** [comment]
Thanks Nick. I am new to the alfresco and want to sync document library using cmissync. I can login on this address using same credentials. What all settings or configurations I need to do, to make it work with cmissync..

**Comment by nicolas-raoul** [comment]
Have you considered CmisSync Business? It can be a good choice if you want more support beyond the tutorials and public documentation we provide.

**Comment by monicakumari** [comment]
No, Not yet. But if we need, we'll look for it in future.

Thanks.

**Comment by monicakumari** [comment]
Hello Nick. 

I have tried another address and it is working fine for me. the only issue I am facing is, It is not updating office files like word file, excel file. 
It is syncing the creation of these files. when I create a new file on my machine inside cmissync folder, these are syncing and uploaded automatically but If I make some changes in word or excel file, Its not updating my document library.It is not updating the files on instance. this issue is with only office documents. could you please help me with this ?

Thanks.
